CREATE TABLE [dbo].[APDownPayments] (
    [UserSign]                         SMALLINT        NULL,
    [U_TRSR_Country]                   NVARCHAR (10)   NULL,
    [U_season]                         NVARCHAR (10)   NULL,
    [U_PAY_BANK_ACC_NO]                NVARCHAR (25)   NULL,
    [U_PAYEE_NAME]                     NVARCHAR (50)   NULL,
    [U_BANK_CODE]                      NVARCHAR (25)   NULL,
    [U_PAYEE_BANK]                     NVARCHAR (100)  NULL,
    [ItemCode]                         NVARCHAR (50)   NULL,
    [CountryCode]                      NVARCHAR (20)   NULL,
    [Comments]                         NVARCHAR (254)  NULL,
    [Currency]                         NVARCHAR (3)    NULL,
    [Text]                             NVARCHAR (MAX)  NULL,
    [DocumentNumber]                   INT             NULL,
    [DocumentDate]                     DATETIME        NULL,
    [DocumentEntry]                    INT             NULL,
    [CustomerSatisfaction]             NVARCHAR (50)   NULL,
    [DocumentStatus]                   VARCHAR (1)     NULL,
    [DocumentDraftInternalID]          INT             NULL,
    [DocumentTotal]                    NUMERIC (19, 6) NULL,
    [LocationCode]                     NVARCHAR (8)    NULL,
    [RowNumber]                        INT             NULL,
    [Canceled]                         VARCHAR (1)     NULL,
    [BaseDocumentReference]            NVARCHAR (16)   NULL,
    [BaseRow]                          INT             NULL,
    [BaseDocumentType]                 INT             NULL,
    [DocumentOwner]                    INT             NULL,
    [Quantity]                         NUMERIC (19, 6) NULL,
    [U_U_Payment_Requested]            NVARCHAR (10)   NULL,
    [CreateDate]                       DATETIME        NULL,
    [DocumentTotalForeignCurrency]     NUMERIC (19, 6) NULL,
    [BusinessPartnerName]              NVARCHAR (100)  NULL,
    [DocumentManuallyClosed]           VARCHAR (1)     NULL,
    [RowTotal]                         NUMERIC (19, 6) NULL,
    [Description]                      NVARCHAR (100)  NULL,
    [AttachmentEntry]                  INT             NULL,
    [DocumentCurrency]                 NVARCHAR (10)   NULL,
    [RowTotalForeignCurrency]          NUMERIC (19, 6) NULL,
    [WarehouseCode]                    NVARCHAR (8)    NULL,
    [U_Requestor]                      NVARCHAR (50)   NULL,
    [U_InputsApprover]                 NVARCHAR (3)    NULL,
    [ObjectType]                       NVARCHAR (20)   NULL,
    [PurQuotationRequiredDate]         DATETIME        NULL,
    [DocumentDueDate]                  DATETIME        NULL,
    [SalesEmployeeCode]                INT             NULL,
    [RowTotalUSD]                      NUMERIC (19, 6) NULL,
    [DepartmentCode]                   NVARCHAR (8)    NULL,
    [AccountCode]                      NVARCHAR (15)   NULL,
    [BusinessPartnerCode]              NVARCHAR (15)   NULL,
    [TransactionID]                    INT             NULL,
    [CurrencyID]                       INT             NULL,
    [CountryID]                        INT             NULL,
    [LocationID]                       INT             NULL,
    [DepartmentID]                     INT             NULL,
    [ItemID]                           INT             NULL,
    [VendorID]                         INT             NULL,
    [CreateDateID]                     INT             NULL,
    [DocumentDateID]                   INT             NULL,
    [UpdateDate]                       DATETIME        NULL,
    [UpdateDateID]                     INT             NULL,
    [WTaxAmount]                       NUMERIC (19, 6) NULL,
    [WTaxAmountUSD]                    NUMERIC (19, 6) NULL,
    [WTaxAmountForeignCurrency]        NUMERIC (19, 6) NULL,
    [TotalDiscountUSD]                 NUMERIC (19, 6) NULL,
    [DownPaymentPercent]               NUMERIC (19, 6) NULL,
    [DownPaymentAmount]                NUMERIC (19, 6) NULL,
    [DownPaymentAmountForeignCurrency] NUMERIC (19, 6) NULL,
    [DownPaymentAmountUSD]             NUMERIC (19, 6) NULL,
    [DocumentTotalUSD]                 NUMERIC (19, 6) NULL,
    [U_WebProcNumber]                  INT             NULL,
    [TotalDiscount]                    NUMERIC (19, 6) NULL,
    [TotalDiscountForeignCurrency]     NUMERIC (19, 6) NULL,
    [Price]                            NUMERIC (19, 6) NULL,
    [ReceiptNum]                       INT             NULL,
    [U_U_DP_DATE]                      DATETIME        NULL,
    [U_Purchaser]                      NVARCHAR (30)   NULL,
    [U_WebPRID]                        INT             NULL,
    [BaseDocumentEntry]                INT             NULL,
    [U_Payment_Request_Date]           DATETIME        NULL,
    [VatSum]                           NUMERIC (19, 6) NULL,
    [VatSumForeignCurrency]            NUMERIC (19, 6) NULL,
    [CreateTime]                       INT             NULL,
    [UpdateTime]                       INT             NULL,
    [UserSignature2]                   SMALLINT        NULL,
    [DocumentSubmissionDate]           DATETIME        NULL,
    [VendorReferenceNo]                NVARCHAR (100)  NULL
);


GO
CREATE NONCLUSTERED INDEX [APDP_IDX]
    ON [dbo].[APDownPayments]([CountryCode] ASC)
    INCLUDE([DocumentEntry], [Canceled], [BusinessPartnerName], [AttachmentEntry], [BusinessPartnerCode], [DownPaymentPercent], [DownPaymentAmount]);

