CREATE TABLE [dbo].[BusinessPartners] (
    [CountryCode]                  NVARCHAR (20)  NULL,
    [GroupCode]                    SMALLINT       NULL,
    [Address]                      NVARCHAR (100) NULL,
    [Phone1]                       NVARCHAR (20)  NULL,
    [Currency]                     NVARCHAR (3)   NULL,
    [City]                         NVARCHAR (100) NULL,
    [County]                       NVARCHAR (100) NULL,
    [Country]                      NVARCHAR (3)   NULL,
    [E_Mail]                       NVARCHAR (100) NULL,
    [CreateDate]                   DATETIME       NULL,
    [UpdateDate]                   DATETIME       NULL,
    [validFor]                     VARCHAR (1)    NULL,
    [Block]                        NVARCHAR (100) NULL,
    [MailAddres]                   NVARCHAR (100) NULL,
    [Phone2]                       NVARCHAR (20)  NULL,
    [Fax]                          NVARCHAR (20)  NULL,
    [MailCity]                     NVARCHAR (100) NULL,
    [MailCounty]                   NVARCHAR (100) NULL,
    [BankCode]                     NVARCHAR (30)  NULL,
    [DataSource]                   VARCHAR (1)    NULL,
    [ExemptNo]                     NVARCHAR (50)  NULL,
    [Priority]                     INT            NULL,
    [CreditCard]                   SMALLINT       NULL,
    [validFrom]                    DATETIME       NULL,
    [validTo]                      DATETIME       NULL,
    [frozenFor]                    VARCHAR (1)    NULL,
    [State1]                       NVARCHAR (3)   NULL,
    [State2]                       NVARCHAR (3)   NULL,
    [Indicator]                    NVARCHAR (2)   NULL,
    [MailBlock]                    NVARCHAR (100) NULL,
    [BackOrder]                    VARCHAR (1)    NULL,
    [AgentCode]                    NVARCHAR (32)  NULL,
    [Industry]                     NVARCHAR (MAX) NULL,
    [Business]                     NVARCHAR (MAX) NULL,
    [IsDomestic]                   VARCHAR (1)    NULL,
    [IsResident]                   VARCHAR (1)    NULL,
    [AliasName]                    NVARCHAR (MAX) NULL,
    [BoEPrsnt]                     NVARCHAR (15)  NULL,
    [Profession]                   NVARCHAR (50)  NULL,
    [StreetNo]                     NVARCHAR (100) NULL,
    [Affiliate]                    VARCHAR (1)    NULL,
    [Series]                       SMALLINT       NULL,
    [Number]                       INT            NULL,
    [Attachment]                   NVARCHAR (MAX) NULL,
    [MandateID]                    NVARCHAR (35)  NULL,
    [U_Approval]                   NVARCHAR (15)  NULL,
    [BusinessPartnerCode]          NVARCHAR (15)  NULL,
    [BusinessPartnerName]          NVARCHAR (100) NULL,
    [BusinessPartnerType]          VARCHAR (1)    NULL,
    [CompanyPrivateGovernment]     VARCHAR (1)    NULL,
    [ContactPerson]                NVARCHAR (90)  NULL,
    [Remarks]                      NVARCHAR (100) NULL,
    [TaxDefinition]                VARCHAR (1)    NULL,
    [FederalTaxID]                 NVARCHAR (32)  NULL,
    [LiableForDeduction]           VARCHAR (1)    NULL,
    [PriceListNumber]              SMALLINT       NULL,
    [CommissionGroup]              SMALLINT       NULL,
    [FreeText]                     NVARCHAR (MAX) NULL,
    [SalesEmployeeCode]            INT            NULL,
    [MobileNumber]                 NVARCHAR (50)  NULL,
    [MailCountry]                  NVARCHAR (3)   NULL,
    [DefaultAccount]               NVARCHAR (50)  NULL,
    [DefaultBranch]                NVARCHAR (50)  NULL,
    [AddiionalIDNo]                NVARCHAR (64)  NULL,
    [ForeignName]                  NVARCHAR (100) NULL,
    [ParentSummaryType]            VARCHAR (1)    NULL,
    [CreditCardNumber]             NVARCHAR (64)  NULL,
    [UserSignature]                SMALLINT       NULL,
    [LCReconciliation]             VARCHAR (1)    NULL,
    [WithholdingTaxdeductionGroup] INT            NULL,
    [CurrentDeductionHierarchy]    INT            NULL,
    [ActiveRemarks]                NVARCHAR (30)  NULL,
    [InactiveRemarks]              NVARCHAR (30)  NULL,
    [DiscountInReturns]            VARCHAR (1)    NULL,
    [LogInstance]                  INT            NULL,
    [ObjectType]                   NVARCHAR (20)  NULL,
    [ShippingType]                 SMALLINT       NULL,
    [AccountsRecievablePayable]    NVARCHAR (15)  NULL,
    [ShiptoDefault]                NVARCHAR (50)  NULL,
    [DocumentEntry]                INT            NULL,
    [1099FormCode]                 INT            NULL,
    [PaymentMethodcode]            NVARCHAR (15)  NULL,
    [PartialDelivery]              VARCHAR (1)    NULL,
    [BankCountry]                  NVARCHAR (3)   NULL,
    [CollectionAuthorization]      VARCHAR (1)    NULL,
    [PaymentBlockDescription]      INT            NULL,
    [HouseBankCountry]             NVARCHAR (3)   NULL,
    [ProjectCode]                  NVARCHAR (20)  NULL,
    [LastSystemReconcilliationNo]  INT            NULL,
    [UnifiedFederalTaxID]          NVARCHAR (32)  NULL,
    [ToleranceDays]                SMALLINT       NULL,
    [DeferredTax]                  VARCHAR (1)    NULL,
    [ExemptionValidityDateTo]      DATETIME       NULL,
    [SubjectToWithholdingTax]      VARCHAR (1)    NULL,
    [BPTypeforWTaxReport]          VARCHAR (1)    NULL,
    [VATRegistrationNumber]        NVARCHAR (32)  NULL,
    [AutoCalculatedBankCharges]    VARCHAR (1)    NULL,
    [OtherRecievableOrPayable]     NVARCHAR (15)  NULL,
    [IncomeTaxWTaxCode]            NVARCHAR (4)   NULL,
    [BillToDefault]                NVARCHAR (50)  NULL,
    [PaymentAdvances]              NVARCHAR (15)  NULL,
    [WebSite]                      NVARCHAR (100) NULL,
    [LanguageCode]                 INT            NULL,
    [HouseBankAccountKey]          INT            NULL,
    [DefaultBankKey]               INT            NULL,
    [BankChargesAllocationCode]    NVARCHAR (3)   NULL,
    [WtaxVericationNo]             NVARCHAR (32)  NULL,
    [DefaultBankInternalID]        NVARCHAR (2)   NULL,
    [BillToAddressType]            NVARCHAR (100) NULL,
    [347InsuranceOperation]        VARCHAR (1)    NULL,
    [ShipToAddressType]            NVARCHAR (100) NULL,
    [TaxRoundingRule]              VARCHAR (1)    NULL,
    [347OperationCode]             VARCHAR (1)    NULL,
    [DPMInterimAccount]            NVARCHAR (15)  NULL,
    [ResidenceNumber]              VARCHAR (1)    NULL,
    [UpdatingUser]                 SMALLINT       NULL,
    [MizvarkExportStatus]          VARCHAR (1)    NULL,
    [HierarchicalDeduction]        VARCHAR (1)    NULL,
    [WithholdingTaxCertified]      VARCHAR (1)    NULL,
    [WithholdingShaamGroup]        VARCHAR (1)    NULL,
    [DATEVAccount]                 INT            NULL,
    [FirstDataEntry]               VARCHAR (1)    NULL,
    [GTSRegistrationNumber]        NVARCHAR (20)  NULL,
    [DefaultBankSwiftCode]         NVARCHAR (50)  NULL,
    [DefaultBankIBAN]              NVARCHAR (50)  NULL,
    [TaxIDCategory]                VARCHAR (1)    NULL,
    [AttachmentEntry]              INT            NULL,
    [DiscRelations]                VARCHAR (1)    NULL,
    [SCAdjustment]                 VARCHAR (1)    NULL,
    [GlobalLocationNumber]         NVARCHAR (50)  NULL,
    [GroupName]                    NVARCHAR (20)  NULL,
    [GroupType]                    VARCHAR (1)    NULL,
    [IndustryC]                    INT            NULL,
    [VendorID]                     INT            NULL,
    [CurrencyID]                   INT            NULL,
    [CountryID]                    INT            NULL,
    [DateID]                       INT            NULL,
    [WebVendorID]                  INT            NULL
);

