CREATE TABLE [dbo].[Capitalizations] (
    [DataSource]                  VARCHAR (1)     NULL,
    [UserSignature]               SMALLINT        NULL,
    [LogInstance]                 INT             NULL,
    [CreateDate]                  DATETIME        NULL,
    [UpdatingUser]                SMALLINT        NULL,
    [UpdateDate]                  DATETIME        NULL,
    [DocumentEntry]               INT             NULL,
    [DocumentNumber]              INT             NULL,
    [Series]                      INT             NULL,
    [DocumentDate]                DATETIME        NULL,
    [DocumentStatus]              VARCHAR (1)     NULL,
    [TransactionID]               INT             NULL,
    [Comments]                    NVARCHAR (254)  NULL,
    [Reference]                   NVARCHAR (32)   NULL,
    [ObjectType]                  NVARCHAR (20)   NULL,
    [Currency]                    NVARCHAR (3)    NULL,
    [DocumentRate]                NUMERIC (19, 6) NULL,
    [SystemPrice]                 NUMERIC (19, 6) NULL,
    [DocumentTotal]               NUMERIC (19, 6) NULL,
    [DocumentTotalFC]             NUMERIC (19, 6) NULL,
    [DocumentTotalUSD]            NUMERIC (19, 6) NULL,
    [TransactionType]             NVARCHAR (20)   NULL,
    [CreatedBy]                   INT             NULL,
    [AssetDate]                   DATETIME        NULL,
    [DocumentType]                NVARCHAR (15)   NULL,
    [Handwrtten]                  VARCHAR (1)     NULL,
    [CancelDate]                  DATETIME        NULL,
    [LVARetire]                   VARCHAR (1)     NULL,
    [PeriodCategory]              NVARCHAR (10)   NULL,
    [PostingPeriod]               INT             NULL,
    [PostingDate]                 DATETIME        NULL,
    [PeriodIndicator]             NVARCHAR (10)   NULL,
    [JournalRemarks]              NVARCHAR (50)   NULL,
    [BaseCurrency]                VARCHAR (1)     NULL,
    [SummarizeByProject]          VARCHAR (1)     NULL,
    [SummarizeByDistributionRule] VARCHAR (1)     NULL,
    [ManualDepreciationType]      NVARCHAR (15)   NULL,
    [DepreciationArea]            NVARCHAR (15)   NULL,
    [Branch]                      INT             NULL,
    [BaseReference]               NVARCHAR (11)   NULL,
    [CancelationOption]           SMALLINT        NULL,
    [BranchName]                  NVARCHAR (100)  NULL,
    [VATRegistrationNumber]       NVARCHAR (32)   NULL,
    [GoodsMovementType]           NVARCHAR (2)    NULL,
    [CountryCode]                 NVARCHAR (3)    NULL
);

