CREATE TABLE [dbo].[DimItem] (
    [ItemID]             INT             IDENTITY (1, 1) NOT NULL,
    [Item_Code]          NVARCHAR (60)   NOT NULL,
    [ItemName]           NVARCHAR (100)  NULL,
    [ItmsGrpCod]         SMALLINT        NULL,
    [ItmsGrpNam]         NVARCHAR (20)   NULL,
    [SellItem]           CHAR (1)        NULL,
    [InvntItem]          CHAR (1)        NULL,
    [DfltWH]             NVARCHAR (8)    NULL,
    [BuyUnitMsr]         NVARCHAR (100)  NULL,
    [SalUnitMsr]         NVARCHAR (100)  NULL,
    [InvntryUom]         NVARCHAR (100)  NULL,
    [U_SUB_GR]           NVARCHAR (40)   NULL,
    [Status]             VARCHAR (8)     NULL,
    [CountryCode]        NVARCHAR (10)   NULL,
    [CountryName]        NTEXT           NULL,
    [CountryID]          INT             NULL,
    [U_Item_Visibility]  NVARCHAR (10)   NULL,
    [ProcurementMethod]  VARCHAR (1)     NULL,
    [PurchaseItem]       VARCHAR (3)     NULL,
    [ExpenseAccount]     NVARCHAR (15)   NULL,
    [IWeight1]           NUMERIC (19, 6) NULL,
    [AttachmentEntry]    INT             NULL,
    [CreateDate]         DATETIME        NULL,
    [CreateDateID]       INT             NULL,
    [ItemCode]           NVARCHAR (50)   NULL,
    [WebItemId]          INT             NULL,
    [WebItemCategoryID]  INT             NULL,
    [UOMGroup]           NVARCHAR (20)   NULL,
    [AssetClass]         NVARCHAR (20)   NULL,
    [CapitalizationDate] DATETIME        NULL,
    [AcquisitionDate]    DATETIME        NULL,
    [Itemtype]           VARCHAR (1)     NULL,
    [DataSource]         VARCHAR (1)     NULL
);

