CREATE TABLE [dbo].[OINC] (
    [UserSign]          SMALLINT        NULL,
    [CreateDate]        DATETIME        NULL,
    [UpdateDate]        DATETIME        NULL,
    [DocEntry]          INT             NULL,
    [UserSign2]         SMALLINT        NULL,
    [DocNum]            INT             NULL,
    [Series]            SMALLINT        NULL,
    [CountDate]         DATETIME        NULL,
    [Time]              INT             NULL,
    [CountType]         VARCHAR (1)     NULL,
    [Taker1Type]        INT             NULL,
    [Taker1Id]          INT             NULL,
    [Taker2Type]        INT             NULL,
    [Taker2Id]          INT             NULL,
    [Status]            VARCHAR (1)     NULL,
    [Ref2]              NVARCHAR (11)   NULL,
    [Remarks]           NTEXT           NULL,
    [LogIns]            INT             NULL,
    [ObjType]           NVARCHAR (20)   NULL,
    [WddStatus]         VARCHAR (1)     NULL,
    [DraftKey]          INT             NULL,
    [Printed]           VARCHAR (1)     NULL,
    [BPLId]             INT             NULL,
    [BPLName]           NVARCHAR (100)  NULL,
    [TeamCount]         INT             NULL,
    [IndvCount]         INT             NULL,
    [DiffQty]           NUMERIC (19, 6) NULL,
    [DiffPercen]        NUMERIC (19, 6) NULL,
    [UpdateTS]          INT             NULL,
    [CreateTime]        SMALLINT        NULL,
    [PIndicator]        NVARCHAR (10)   NULL,
    [FinncPriod]        INT             NULL,
    [PostDate]          DATETIME        NULL,
    [VersionNum]        NVARCHAR (11)   NULL,
    [DataSource]        VARCHAR (1)     NULL,
    [U_Attachment1]     NTEXT           NULL,
    [U_Attachment2]     NTEXT           NULL,
    [CountryCode]       NVARCHAR (3)    NULL,
    [ItemCode]          NVARCHAR (50)   NULL,
    [ItemName]          NVARCHAR (100)  NULL,
    [FrgnName]          NVARCHAR (100)  NULL,
    [ItmsGrpCod]        SMALLINT        NULL,
    [VatGourpSa]        NVARCHAR (8)    NULL,
    [SellItem]          VARCHAR (1)     NULL,
    [InvntItem]         VARCHAR (1)     NULL,
    [OnHand]            NUMERIC (19, 6) NULL,
    [IsCommited]        NUMERIC (19, 6) NULL,
    [OnOrder]           NUMERIC (19, 6) NULL,
    [MaxLevel]          NUMERIC (19, 6) NULL,
    [DfltWH]            NVARCHAR (8)    NULL,
    [BuyUnitMsr]        NVARCHAR (100)  NULL,
    [SalUnitMsr]        NVARCHAR (100)  NULL,
    [Counted]           NUMERIC (19, 6) NULL,
    [VatGroupPu]        NVARCHAR (8)    NULL,
    [GLMethod]          VARCHAR (1)     NULL,
    [UgpEntry]          INT             NULL,
    [U_SUB_GR]          NVARCHAR (40)   NULL,
    [U_Item_Visibility] NVARCHAR (10)   NULL,
    [ValidFor]          VARCHAR (1)     NULL,
    [ValidFrom]         DATETIME        NULL,
    [ValidTo]           DATETIME        NULL,
    [PrchseItem]        VARCHAR (1)     NULL,
    [InVntryUom]        NVARCHAR (100)  NULL,
    [PUomEntry]         INT             NULL,
    [atcentry]          INT             NULL
);

