CREATE TABLE [dbo].[OWHS] (
    [WhsCode]     NVARCHAR (8)   NOT NULL,
    [WhsName]     NVARCHAR (100) NULL,
    [BalInvntAc]  NVARCHAR (15)  NULL,
    [SaleCostAc]  NVARCHAR (15)  NULL,
    [TransferAc]  NVARCHAR (15)  NULL,
    [Locked]      CHAR (1)       NULL,
    [DataSource]  CHAR (1)       NULL,
    [UserSign]    SMALLINT       NULL,
    [RevenuesAc]  NVARCHAR (15)  NULL,
    [VarianceAc]  NVARCHAR (15)  NULL,
    [DecreasAc]   NVARCHAR (15)  NULL,
    [IncreasAc]   NVARCHAR (15)  NULL,
    [ReturnAc]    NVARCHAR (15)  NULL,
    [ExpensesAc]  NVARCHAR (15)  NULL,
    [EURevenuAc]  NVARCHAR (15)  NULL,
    [EUExpensAc]  NVARCHAR (15)  NULL,
    [FrRevenuAc]  NVARCHAR (15)  NULL,
    [FrExpensAc]  NVARCHAR (15)  NULL,
    [Country]     NVARCHAR (3)   NULL,
    [Location]    INT            NULL,
    [UseTax]      CHAR (1)       NULL,
    [PriceDifAc]  NVARCHAR (15)  NULL,
    [ExchangeAc]  NVARCHAR (15)  NULL,
    [BalanceAcc]  NVARCHAR (15)  NULL,
    [DecresGlAc]  NVARCHAR (15)  NULL,
    [IncresGlAc]  NVARCHAR (15)  NULL,
    [Nettable]    CHAR (1)       NULL,
    [WipAcct]     NVARCHAR (15)  NULL,
    [WipVarAcct]  NVARCHAR (15)  NULL,
    [objType]     NVARCHAR (20)  NULL,
    [createDate]  DATETIME       NULL,
    [userSign2]   SMALLINT       NULL,
    [updateDate]  DATETIME       NULL,
    [ARCMAct]     NVARCHAR (15)  NULL,
    [ARCMFrnAct]  NVARCHAR (15)  NULL,
    [ARCMEUAct]   NVARCHAR (15)  NULL,
    [APCMAct]     NVARCHAR (15)  NULL,
    [APCMFrnAct]  NVARCHAR (15)  NULL,
    [APCMEUAct]   NVARCHAR (15)  NULL,
    [OwnerCode]   CHAR (1)       NULL,
    [NegStckAct]  NVARCHAR (15)  NULL,
    [StkInTnAct]  NVARCHAR (15)  NULL,
    [DftBinAbs]   INT            NULL,
    [DftBinEnfd]  CHAR (1)       NULL,
    [AutoIssMtd]  SMALLINT       NULL,
    [ManageSnB]   CHAR (1)       NULL,
    [RecItemsBy]  SMALLINT       NULL,
    [RecBinEnab]  CHAR (1)       NULL,
    [RecvEmpBin]  CHAR (1)       NULL,
    [Inactive]    CHAR (1)       NULL,
    [RecvMaxQty]  CHAR (1)       NULL,
    [AutoRecvMd]  SMALLINT       NULL,
    [RecvMaxWT]   CHAR (1)       NULL,
    [RecvUpTo]    NVARCHAR (6)   NULL,
    [CountryCode] NVARCHAR (20)  NULL
);

