CREATE TABLE [dbo].[AP_DownPayment] (
    [DocDate]           DATETIME2 (3)   NULL,
    [docentry]          INT             NOT NULL,
    [U_CustSat]         NVARCHAR (20)   NULL,
    [docnum]            INT             NOT NULL,
    [UserSign]          SMALLINT        NULL,
    [canceled]          CHAR (1)        NULL,
    [U_TRSR_Country]    NVARCHAR (10)   NOT NULL,
    [TransID]           INT             NULL,
    [U_season]          NVARCHAR (10)   NULL,
    [U_PAY_BANK_ACC_NO] NVARCHAR (25)   NULL,
    [U_PAYEE_NAME]      NVARCHAR (50)   NULL,
    [U_BANK_CODE]       NVARCHAR (25)   NULL,
    [CardCode]          NVARCHAR (15)   NULL,
    [U_PAYEE_BANK]      NVARCHAR (100)  NULL,
    [DocStatus]         CHAR (1)        NULL,
    [DocManClsd]        CHAR (1)        NULL,
    [LocationCode]      NVARCHAR (8)    NULL,
    [PQTReqDate]        DATETIME2 (3)   NULL,
    [quantity]          DECIMAL (19, 6) NULL,
    [TotalSumSy]        DECIMAL (19, 6) NULL,
    [BaseType]          INT             NULL,
    [baseref]           NVARCHAR (16)   NULL,
    [baseline]          INT             NULL,
    [LineNum]           INT             NULL,
    [ItemCode]          NVARCHAR (50)   NULL,
    [WhsCode]           NVARCHAR (8)    NULL,
    [CountryCode]       NVARCHAR (20)   NULL,
    [Countryid]         INT             NULL,
    [Item_Code]         NVARCHAR (60)   NULL,
    [DateKey]           INT             NULL,
    [Vendor_Key]        INT             NULL,
    [Departmentid]      INT             NULL,
    [DepartmentCode]    NVARCHAR (8)    NULL,
    [Locationid]        INT             NULL
);

