CREATE TABLE [dbo].[APCreditMemos] (
    [DocumentEntry]           INT             NULL,
    [DocumentNumber]          INT             NULL,
    [DocumentDate]            DATETIME        NULL,
    [BusinessPartnerName]     NVARCHAR (100)  NULL,
    [Comments]                NVARCHAR (254)  NULL,
    [BaseDocumentType]        INT             NULL,
    [Canceled]                VARCHAR (1)     NULL,
    [DocumentDraftInternalID] INT             NULL,
    [DocumentTotal]           NUMERIC (19, 6) NULL,
    [CreateDate]              DATETIME        NULL,
    [ObjectType]              NVARCHAR (20)   NULL,
    [DocumentTotalUSD]        NUMERIC (19, 6) NULL,
    [UserSignature]           SMALLINT        NULL,
    [BaseDocumentInternalID]  INT             NULL,
    [CountryCode]             NVARCHAR (50)   NULL,
    [U_InputsApprover]        NVARCHAR (3)    NULL,
    [U_Season]                NVARCHAR (10)   NULL,
    [RowNumber]               INT             NULL,
    [AttachmentEntry]         INT             NULL,
    [ControlAccount]          NVARCHAR (15)   NULL,
    [U_U_DP_DATE]             DATETIME        NULL,
    [U_WebProcNumber]         INT             NULL,
    [U_WebPRID]               INT             NULL,
    [U_Requestor]             NVARCHAR (50)   NULL,
    [U_Purchaser]             NVARCHAR (30)   NULL,
    [CreateTime]              INT             NULL,
    [UpdateTime]              INT             NULL,
    [UserSignature2]          SMALLINT        NULL,
    [DocumentSubmissionDate]  DATETIME        NULL,
    [U_TRSR_Country]          NVARCHAR (10)   NULL,
    [UpdateDate]              DATETIME        NULL
);

