CREATE TABLE [dbo].[APInvoices] (
    [CANCELED]                            VARCHAR (1)     NULL,
    [InvntSttus]                          VARCHAR (1)     NULL,
    [PaidToDate]                          NUMERIC (19, 6) NULL,
    [Comments]                            NVARCHAR (254)  NULL,
    [Weight]                              NUMERIC (19, 6) NULL,
    [U_PUR_LEVEL]                         NVARCHAR (15)   NULL,
    [U_DP_REQ]                            NVARCHAR (10)   NULL,
    [U_VENDOR_ACCPT]                      NVARCHAR (10)   NULL,
    [U_VENDOR_ACCP_ATTCH]                 NVARCHAR (MAX)  NULL,
    [U_U_INTC_ACC]                        INT             NULL,
    [U_U_PAY_BNK_ACC]                     NVARCHAR (10)   NULL,
    [U_TRSR_COUNTRY]                      NVARCHAR (10)   NULL,
    [U_QUOTE_ONLY]                        NVARCHAR (10)   NULL,
    [U_PAY_STATUS]                        NVARCHAR (10)   NULL,
    [U_PAY_NUM]                           NVARCHAR (50)   NULL,
    [U_DATE_DIS]                          DATETIME        NULL,
    [U_COR_BW_FromDate]                   DATETIME        NULL,
    [U_COR_BW_ToDate]                     DATETIME        NULL,
    [U_PRTY_LVL]                          NVARCHAR (20)   NULL,
    [U_LANDED_CST_PO]                     INT             NULL,
    [U_TRSFR_LC_NO]                       INT             NULL,
    [U_DP_PER]                            NUMERIC (19, 6) NULL,
    [U_I1_PER]                            NUMERIC (19, 6) NULL,
    [U_I2_PER]                            NUMERIC (19, 6) NULL,
    [U_I3_PER]                            NUMERIC (19, 6) NULL,
    [U_I4_PER]                            NUMERIC (19, 6) NULL,
    [U_I5_PER]                            NUMERIC (19, 6) NULL,
    [U_APP_DOC_ATTCH]                     NVARCHAR (MAX)  NULL,
    [U_REQUEST_APP]                       NVARCHAR (10)   NULL,
    [U_PAYEE_NAME]                        NVARCHAR (50)   NULL,
    [U_PAYEE_BANK]                        NVARCHAR (200)  NULL,
    [U_PAY_BANK_ACC_NO]                   NVARCHAR (25)   NULL,
    [U_DP2_PER]                           NUMERIC (19, 6) NULL,
    [U_DP3_PER]                           NUMERIC (19, 6) NULL,
    [U_USE_DP]                            INT             NULL,
    [U_BANK_CODE]                         NVARCHAR (25)   NULL,
    [U_Season]                            NVARCHAR (30)   NULL,
    [ItemCode]                            NVARCHAR (50)   NULL,
    [Quantity]                            NUMERIC (19, 6) NULL,
    [ShipDate]                            DATETIME        NULL,
    [Price]                               NUMERIC (19, 6) NULL,
    [Commission]                          NUMERIC (19, 6) NULL,
    [TreeType]                            VARCHAR (1)     NULL,
    [TaxStatus]                           VARCHAR (1)     NULL,
    [Flags]                               INT             NULL,
    [Project]                             NVARCHAR (20)   NULL,
    [Height1]                             NUMERIC (19, 6) NULL,
    [Width1]                              NUMERIC (19, 6) NULL,
    [Width2]                              NUMERIC (19, 6) NULL,
    [Volume]                              NUMERIC (19, 6) NULL,
    [VolUnit]                             SMALLINT        NULL,
    [Weight1]                             NUMERIC (19, 6) NULL,
    [Weight2]                             NUMERIC (19, 6) NULL,
    [Factor1]                             NUMERIC (19, 6) NULL,
    [Factor2]                             NUMERIC (19, 6) NULL,
    [Factor3]                             NUMERIC (19, 6) NULL,
    [Factor4]                             NUMERIC (19, 6) NULL,
    [DropShip]                            VARCHAR (1)     NULL,
    [Address]                             NVARCHAR (254)  NULL,
    [TaxCode]                             NVARCHAR (8)    NULL,
    [TaxType]                             VARCHAR (1)     NULL,
    [PickStatus]                          VARCHAR (1)     NULL,
    [TaxPerUnit]                          NUMERIC (19, 6) NULL,
    [Text]                                NVARCHAR (MAX)  NULL,
    [StockSum]                            NUMERIC (19, 6) NULL,
    [ShipToCode]                          NVARCHAR (50)   NULL,
    [OcrCode4]                            NVARCHAR (8)    NULL,
    [OcrCode5]                            NVARCHAR (8)    NULL,
    [PostTax]                             VARCHAR (1)     NULL,
    [Excisable]                           VARCHAR (1)     NULL,
    [CSTfIPI]                             NVARCHAR (2)    NULL,
    [CSTfPIS]                             NVARCHAR (2)    NULL,
    [CSTfCOFINS]                          NVARCHAR (2)    NULL,
    [ExLineNo]                            NVARCHAR (10)   NULL,
    [isSrvCall]                           VARCHAR (1)     NULL,
    [UomEntry]                            INT             NULL,
    [UomCode]                             NVARCHAR (20)   NULL,
    [Incoterms]                           INT             NULL,
    [U_WIP_PROJECT]                       NVARCHAR (30)   NULL,
    [U_SBSD_CODE]                         NVARCHAR (30)   NULL,
    [CountryCode]                         NVARCHAR (20)   NULL,
    [DepartmentCode]                      NVARCHAR (8)    NULL,
    [LocationCode]                        NVARCHAR (8)    NULL,
    [U_CusotmerSat]                       NVARCHAR (20)   NULL,
    [U_CusotmerSat2]                      NVARCHAR (20)   NULL,
    [DocumentEntry]                       INT             NULL,
    [DocumentNumber]                      INT             NULL,
    [DocumentType]                        VARCHAR (1)     NULL,
    [DocumentStatus]                      VARCHAR (1)     NULL,
    [ObjectType]                          NVARCHAR (20)   NULL,
    [DocumentDate]                        DATETIME        NULL,
    [DocumentDueDate]                     DATETIME        NULL,
    [BusinessPartnerCode]                 NVARCHAR (15)   NULL,
    [BusinessPartnerName]                 NVARCHAR (100)  NULL,
    [DocumentTotal]                       NUMERIC (19, 6) NULL,
    [TransactionID]                       INT             NULL,
    [ReceiptNumber]                       INT             NULL,
    [UserSignature]                       SMALLINT        NULL,
    [ControlAccount]                      NVARCHAR (15)   NULL,
    [TotalPaidSum]                        NUMERIC (19, 6) NULL,
    [DocumentOwner]                       INT             NULL,
    [DocumentClosedManually]              VARCHAR (1)     NULL,
    [CreateDate]                          DATETIME        NULL,
    [UpdateDate]                          DATETIME        NULL,
    [AttachmentEntry]                     INT             NULL,
    [RowNumber]                           INT             NULL,
    [TargetDocumentType]                  INT             NULL,
    [TargetDocumentInternalID]            INT             NULL,
    [BaseDocumentReference]               NVARCHAR (16)   NULL,
    [BaseDocumentType]                    INT             NULL,
    [BaseDocumentInternalID]              INT             NULL,
    [BaseRow]                             INT             NULL,
    [RowStatus]                           VARCHAR (1)     NULL,
    [Description]                         NVARCHAR (100)  NULL,
    [RemainingOpenQuantity]               NUMERIC (19, 6) NULL,
    [PriceCurrency]                       NVARCHAR (3)    NULL,
    [CurrencyRate]                        NUMERIC (19, 6) NULL,
    [DiscountPercent]                     NUMERIC (19, 6) NULL,
    [RowTotalLocal]                       NUMERIC (19, 6) NULL,
    [OpenRowAmount]                       NUMERIC (19, 6) NULL,
    [VendorCatalogNumber]                 NVARCHAR (50)   NULL,
    [SerialNumber]                        NVARCHAR (17)   NULL,
    [WarehouseCode]                       NVARCHAR (8)    NULL,
    [SalesEmployeeCode]                   INT             NULL,
    [AccountCode]                         NVARCHAR (15)   NULL,
    [GrossProfitBasePrice]                NUMERIC (19, 6) NULL,
    [UnitPrice]                           NUMERIC (19, 6) NULL,
    [CreditMemoAmount]                    NUMERIC (19, 6) NULL,
    [InventoryUOM]                        VARCHAR (1)     NULL,
    [BaseBusinessPartnerCode]             NVARCHAR (15)   NULL,
    [DistributionRule]                    NVARCHAR (8)    NULL,
    [TaxRatePerRow]                       NUMERIC (19, 6) NULL,
    [TaxDefinition]                       NVARCHAR (8)    NULL,
    [GrossPrice]                          NUMERIC (19, 6) NULL,
    [Height2Unit]                         SMALLINT        NULL,
    [Weight1Unit]                         SMALLINT        NULL,
    [Weight2Unit]                         SMALLINT        NULL,
    [PackingQuantity]                     NUMERIC (19, 6) NULL,
    [WarehouseUpdate]                     VARCHAR (1)     NULL,
    [BaseDocumentNumber]                  INT             NULL,
    [BusinessPartnerBaseDocument]         NVARCHAR (100)  NULL,
    [AdditionalIdentifier]                NVARCHAR (16)   NULL,
    [PostingPeriod]                       INT             NULL,
    [BlockNumber]                         NVARCHAR (100)  NULL,
    [DeductibleTaxAmount]                 NUMERIC (19, 6) NULL,
    [AcquisitionTax]                      VARCHAR (1)     NULL,
    [DistributedAmount]                   NUMERIC (19, 6) NULL,
    [RowGrossProfit]                      NUMERIC (19, 6) NULL,
    [VisualOrder]                         INT             NULL,
    [ItemLastSalesPrice]                  NUMERIC (19, 6) NULL,
    [PurchaseOrderTargetNumber]           INT             NULL,
    [PurchaseOrderTargetInternalID]       NVARCHAR (11)   NULL,
    [OriginalItem]                        NVARCHAR (254)  NULL,
    [AllowBackOrder]                      VARCHAR (1)     NULL,
    [FreeText]                            NVARCHAR (100)  NULL,
    [PickQuantity]                        NUMERIC (19, 6) NULL,
    [PickListIDNumber]                    INT             NULL,
    [ShippingMethod]                      SMALLINT        NULL,
    [AppliedTax]                          NUMERIC (19, 6) NULL,
    [BaseQuantity]                        NUMERIC (19, 6) NULL,
    [BaseOpenQuantity]                    NUMERIC (19, 6) NULL,
    [TaxDiscount]                         NUMERIC (19, 6) NULL,
    [WithholdingTaxLiable]                VARCHAR (1)     NULL,
    [DeferredTax]                         VARCHAR (1)     NULL,
    [EqualizationTax]                     NUMERIC (19, 6) NULL,
    [NetTaxAmount]                        NUMERIC (19, 6) NULL,
    [NetTaxAmount2]                       NUMERIC (19, 6) NULL,
    [Unit]                                NVARCHAR (100)  NULL,
    [UOMValue]                            NUMERIC (19, 6) NULL,
    [CorrectionInvoice]                   VARCHAR (1)     NULL,
    [InventoryCorrectionInvoiceAmount]    NUMERIC (19, 6) NULL,
    [TotalIncludingTax]                   NUMERIC (19, 6) NULL,
    [CountryOfOrigin]                     NVARCHAR (3)    NULL,
    [InventoryPrice]                      NUMERIC (19, 6) NULL,
    [ConsumerSalesForecast]               VARCHAR (1)     NULL,
    [LastBuyDistributeSum]                NUMERIC (19, 6) NULL,
    [StockINMPrice]                       NUMERIC (19, 6) NULL,
    [LastBuyDistributionSumFC]            NUMERIC (19, 6) NULL,
    [LastBuyDistributionSumSC]            NUMERIC (19, 6) NULL,
    [StockSumApplied]                     NUMERIC (19, 6) NULL,
    [ShipToDescription]                   NVARCHAR (254)  NULL,
    [StockDistributeAppliedSum]           NUMERIC (19, 6) NULL,
    [StockDistributeAppliedSumFC]         NUMERIC (19, 6) NULL,
    [StockDistributeAppliedSumSC]         NUMERIC (19, 6) NULL,
    [TotalCalculationPrice]               VARCHAR (1)     NULL,
    [GrossRowTotal]                       NUMERIC (19, 6) NULL,
    [DistributeFreight]                   VARCHAR (1)     NULL,
    [DescriptionOverwritten]              VARCHAR (1)     NULL,
    [DetailsOverWritten]                  VARCHAR (1)     NULL,
    [GrossProfitBaseMethod]               SMALLINT        NULL,
    [TaxBeforeDPM]                        NUMERIC (19, 6) NULL,
    [COGSDistributionRule]                NVARCHAR (8)    NULL,
    [OppositeLineNumber]                  INT             NULL,
    [COGSAccountCode]                     NVARCHAR (15)   NULL,
    [ChangeWarehouseBOM]                  VARCHAR (1)     NULL,
    [ActualDeliveryDate]                  DATETIME        NULL,
    [DistributedTaxAmount]                NUMERIC (19, 6) NULL,
    [AssessableValue]                     NUMERIC (19, 6) NULL,
    [TotalProfitBasePrice]                NUMERIC (19, 6) NULL,
    [UOMIfBaseUnit]                       NVARCHAR (100)  NULL,
    [UOMValueIfBaseUnit]                  NUMERIC (19, 6) NULL,
    [PriceSourceType]                     VARCHAR (1)     NULL,
    [PurQuotationReQuiredQuantity]        NUMERIC (19, 6) NULL,
    [PurQuotationRequiredDate]            DATETIME        NULL,
    [PurchaseConfirmationDocType]         INT             NULL,
    [PurchaseConfirmationQuantity]        NUMERIC (19, 6) NULL,
    [LineWasClosedManually]               VARCHAR (1)     NULL,
    [VATGroupSource]                      VARCHAR (1)     NULL,
    [WithoutInventoryMovement]            VARCHAR (1)     NULL,
    [ActualBaseDocumentEntry]             INT             NULL,
    [ActualBaseDocumentLineNumber]        INT             NULL,
    [ActualBaseDocumentNumber]            INT             NULL,
    [UOMEntryIfBaseUnit]                  INT             NULL,
    [UOMCodeIfBaseUnit]                   NVARCHAR (20)   NULL,
    [FromWarehouseCode]                   NVARCHAR (8)    NULL,
    [ConsiderQuantityOfItems]             VARCHAR (1)     NULL,
    [PartialRetirement]                   VARCHAR (1)     NULL,
    [RetirementQuantity]                  NUMERIC (19, 6) NULL,
    [RetirementAPC]                       NUMERIC (19, 6) NULL,
    [InventoryQuantity]                   NUMERIC (19, 6) NULL,
    [OpenInventoryQuantity]               NUMERIC (19, 6) NULL,
    [EnableSetItemCost]                   VARCHAR (1)     NULL,
    [ReturnCost]                          NUMERIC (19, 6) NULL,
    [TransportMode]                       INT             NULL,
    [LineVendorCode]                      NVARCHAR (15)   NULL,
    [DistribureIntrastatFreight]          VARCHAR (1)     NULL,
    [IntrastatDistributeAmount]           NUMERIC (19, 6) NULL,
    [IntrastatDistributeAmountFC]         NUMERIC (19, 6) NULL,
    [IntrastatDistributeAmountSC]         NUMERIC (19, 6) NULL,
    [LinePurchaseOrderProcess]            VARCHAR (1)     NULL,
    [FreeOfChargeBusinessPartner]         VARCHAR (1)     NULL,
    [TaxRelevantRow]                      VARCHAR (1)     NULL,
    [U_Requestor]                         NVARCHAR (50)   NULL,
    [DocumentCurrency]                    NVARCHAR (3)    NULL,
    [DownPaymentPercent]                  NUMERIC (19, 6) NULL,
    [DownPaymentAmount]                   NUMERIC (19, 6) NULL,
    [U_WebProcNumber]                     INT             NULL,
    [U_ARRec]                             NVARCHAR (10)   NULL,
    [U_WHR]                               NVARCHAR (30)   NULL,
    [U_Request_ID]                        NVARCHAR (50)   NULL,
    [TaxDate]                             DATETIME        NULL,
    [U_U_Payment_Requested]               NVARCHAR (10)   NULL,
    [U_InputsApprover]                    NVARCHAR (3)    NULL,
    [WTaxAmount]                          NUMERIC (19, 6) NULL,
    [DocumentTotalUSD]                    NUMERIC (19, 6) NULL,
    [WTaxAmountUSD]                       NUMERIC (19, 6) NULL,
    [DownPaymentAmountUSD]                NUMERIC (19, 6) NULL,
    [RowTotalForeign]                     NUMERIC (19, 6) NULL,
    [OpenRowAmountUSD]                    NUMERIC (19, 6) NULL,
    [TaxAmountUSD]                        NUMERIC (19, 6) NULL,
    [DeductibleTaxAmountUSD]              NUMERIC (19, 6) NULL,
    [DistributedAmountUSD]                NUMERIC (19, 6) NULL,
    [RowGrossProfitUSD]                   NUMERIC (19, 6) NULL,
    [TotalEqualizationTaxUSD]             NUMERIC (19, 6) NULL,
    [StockDistributedSumUSD]              NUMERIC (19, 6) NULL,
    [StockSumUSD]                         NUMERIC (19, 6) NULL,
    [StockSumAppliedUSD]                  NUMERIC (19, 6) NULL,
    [GrossRowTotalUSD]                    NUMERIC (19, 6) NULL,
    [TaxBeforeDPMUSD]                     NUMERIC (19, 6) NULL,
    [DistributedTaxUSD]                   NUMERIC (19, 6) NULL,
    [RetirementAPCUSD]                    NUMERIC (19, 6) NULL,
    [DocumentTotalForeignCurrency]        NUMERIC (19, 6) NULL,
    [PaidForeignCurrency]                 NUMERIC (19, 6) NULL,
    [WTaxAmountForeignCurrency]           NUMERIC (19, 6) NULL,
    [TotalDiscountUSD]                    NUMERIC (19, 6) NULL,
    [DownPaymentAmountForeignCurrency]    NUMERIC (19, 6) NULL,
    [OpenRowAmountForeignCurrency]        NUMERIC (19, 6) NULL,
    [RowTotalUSD]                         NUMERIC (19, 6) NULL,
    [TaxAmountForeignCurrency]            NUMERIC (19, 6) NULL,
    [DeductibleTaxAmountForeignCurrency]  NUMERIC (19, 6) NULL,
    [DistributedAmountForeignCurrency]    NUMERIC (19, 6) NULL,
    [RowGrossProfitForeignCurrency]       NUMERIC (19, 6) NULL,
    [AppliedTaxFForeignCurrency]          NUMERIC (19, 6) NULL,
    [AppliedTaxUSD]                       NUMERIC (19, 6) NULL,
    [TotalEqualizationTaxForeignCurrency] NUMERIC (19, 6) NULL,
    [StockDistributedSumForeignCurrency]  NUMERIC (19, 6) NULL,
    [StockSumForeignCurrency]             NUMERIC (19, 6) NULL,
    [StockSumAppliedForeignCurrency]      NUMERIC (19, 6) NULL,
    [GrossRowTotalForeignCurrency]        NUMERIC (19, 6) NULL,
    [TaxBeforeDPMForeignCurrency]         NUMERIC (19, 6) NULL,
    [DistributedTaxForeignCurrency]       NUMERIC (19, 6) NULL,
    [RetirementAPCForeignCurrency]        NUMERIC (19, 6) NULL,
    [CurrencyID]                          INT             NULL,
    [CountryID]                           INT             NULL,
    [LocationID]                          INT             NULL,
    [DepartmentID]                        INT             NULL,
    [VendorID]                            INT             NULL,
    [DueDateID]                           INT             NULL,
    [CreateDateID]                        INT             NULL,
    [ItemID]                              INT             NULL,
    [DocDateID]                           INT             NULL,
    [Currency]                            NVARCHAR (3)    NULL,
    [U_VendorPerf]                        NVARCHAR (254)  NULL,
    [TotalDiscount]                       NUMERIC (19, 6) NULL,
    [TotalDiscountForeignCurrency]        NUMERIC (19, 6) NULL,
    [U_ICSourceNo]                        INT             NULL,
    [U_ICSourceCntry]                     NVARCHAR (10)   NULL,
    [U_VendorAdd]                         NVARCHAR (35)   NULL,
    [U_U_DP_DATE]                         DATETIME        NULL,
    [U_WebPRID]                           INT             NULL,
    [U_Purchaser]                         NVARCHAR (30)   NULL,
    [BaseDocumentEntry]                   INT             NULL,
    [VatSum]                              NUMERIC (19, 6) NULL,
    [VatSumForeignCurrency]               NUMERIC (19, 6) NULL,
    [ReserveInvoice]                      VARCHAR (1)     NULL,
    [DocumentDraftInternalID]             INT             NULL,
    [CreateTime]                          INT             NULL,
    [UpdateTime]                          INT             NULL,
    [UserSignature2]                      SMALLINT        NULL,
    [DocumentSubmissionDate]              DATETIME        NULL,
    [VendorReferenceNo]                   NVARCHAR (100)  NULL
);


GO
CREATE NONCLUSTERED INDEX [_dta_index_APInvoices_7_1173579219__K259_K1_K55_63_64_166]
    ON [dbo].[APInvoices]([CountryCode] ASC, [DocumentEntry] ASC, [RowNumber] ASC)
    INCLUDE([ItemCode], [Description], [Text]);


GO
CREATE NONCLUSTERED INDEX [APInvoices_IDX]
    ON [dbo].[APInvoices]([CANCELED] ASC, [CountryCode] ASC, [BaseDocumentType] ASC, [BaseRow] ASC)
    INCLUDE([Quantity], [Price], [U_CusotmerSat], [DocumentNumber], [DocumentDate], [RowNumber], [BaseDocumentReference], [RowStatus], [RowTotalLocal], [RowTotalForeign], [Currency]);


GO
CREATE NONCLUSTERED INDEX [APDrafts]
    ON [dbo].[APInvoices]([CountryCode] ASC, [DocumentDraftInternalID] ASC)
    INCLUDE([U_TRSR_COUNTRY], [U_Season], [DocumentEntry], [DocumentNumber], [DocumentDate], [DocumentSubmissionDate]);


GO
CREATE STATISTICS [_dta_stat_242815927_81_82_125]
    ON [dbo].[APInvoices]([CountryCode], [DepartmentCode], [AccountCode]);

