CREATE TABLE [dbo].[ARCreditMemos] (
    [Address]                        NVARCHAR (254)  NULL,
    [PaidToDate]                     NUMERIC (19, 6) NULL,
    [Comments]                       NVARCHAR (254)  NULL,
    [UpdateDate]                     DATETIME        NULL,
    [CreateDate]                     DATETIME        NULL,
    [Weight]                         NUMERIC (19, 6) NULL,
    [Series]                         INT             NULL,
    [TaxDate]                        DATETIME        NULL,
    [DataSource]                     VARCHAR (1)     NULL,
    [ShipToCode]                     NVARCHAR (50)   NULL,
    [Rounding]                       VARCHAR (1)     NULL,
    [Max1099]                        NUMERIC (19, 6) NULL,
    [U_VENDOR_ACCPT]                 NVARCHAR (10)   NULL,
    [U_TRSFR_LC_NO]                  INT             NULL,
    [Project]                        NVARCHAR (20)   NULL,
    [ItemCode]                       NVARCHAR (50)   NULL,
    [Quantity]                       NUMERIC (19, 6) NULL,
    [ShipDate]                       DATETIME        NULL,
    [Price]                          NUMERIC (19, 6) NULL,
    [Currency]                       NVARCHAR (3)    NULL,
    [Weight1]                        NUMERIC (19, 6) NULL,
    [Factor1]                        NUMERIC (19, 6) NULL,
    [Factor2]                        NUMERIC (19, 6) NULL,
    [Factor3]                        NUMERIC (19, 6) NULL,
    [Factor4]                        NUMERIC (19, 6) NULL,
    [StockSum]                       NUMERIC (19, 6) NULL,
    [U_WIP_PROJECT]                  NVARCHAR (30)   NULL,
    [U_SBSD_CODE]                    NVARCHAR (30)   NULL,
    [CountryCode]                    NVARCHAR (2)    NULL,
    [Text]                           NVARCHAR (MAX)  NULL,
    [DocumentEntry]                  INT             NULL,
    [DocumentNumber]                 INT             NULL,
    [DocumentType]                   VARCHAR (1)     NULL,
    [Canceled]                       VARCHAR (1)     NULL,
    [DocumentStatus]                 VARCHAR (1)     NULL,
    [WarehouseStatus]                VARCHAR (1)     NULL,
    [DocumentDate]                   DATETIME        NULL,
    [DocumentDueDate]                DATETIME        NULL,
    [BusinessPartnerCode]            NVARCHAR (15)   NULL,
    [BusinessPartnerName]            NVARCHAR (100)  NULL,
    [BusinessPartnerReferenceNumber] NVARCHAR (100)  NULL,
    [DiscountPercentage]             NUMERIC (19, 6) NULL,
    [TotalDiscount]                  NUMERIC (19, 6) NULL,
    [DocumentCurrency]               NVARCHAR (3)    NULL,
    [DocumentRate]                   NUMERIC (19, 6) NULL,
    [DocumentTotal]                  NUMERIC (19, 6) NULL,
    [DocumentTotalForeignCurrency]   NUMERIC (19, 6) NULL,
    [GrossProfit]                    NUMERIC (19, 6) NULL,
    [Reference1]                     NVARCHAR (11)   NULL,
    [JournalRemarks]                 NVARCHAR (50)   NULL,
    [TransactionID]                  INT             NULL,
    [ReceiptNumber]                  INT             NULL,
    [GenerationTime]                 SMALLINT        NULL,
    [SalesEmployee]                  INT             NULL,
    [ContactPerson]                  INT             NULL,
    [SyatemPrice]                    NUMERIC (19, 6) NULL,
    [BaseCurrency]                   VARCHAR (1)     NULL,
    [PostingPeriod]                  INT             NULL,
    [UserSignature]                  SMALLINT        NULL,
    [UserSignature2]                 SMALLINT        NULL,
    [DocumentDraftInternalID]        INT             NULL,
    [ShipTo]                         NVARCHAR (254)  NULL,
    [WorkstationID]                  INT             NULL,
    [LicensedDealerNumber]           NVARCHAR (32)   NULL,
    [BlockCreationTarget]            VARCHAR (1)     NULL,
    [ControlAccount]                 NVARCHAR (15)   NULL,
    [DownPaymentAmount]              NUMERIC (19, 6) NULL,
    [TotalPaidSum]                   NUMERIC (19, 6) NULL,
    [PayTo]                          NVARCHAR (50)   NULL,
    [VersionNumber]                  NVARCHAR (11)   NULL,
    [BPNameOVerWritten]              VARCHAR (1)     NULL,
    [ServiceGrossProfitPercent]      NUMERIC (19, 6) NULL,
    [AttachmentEntry]                INT             NULL,
    [BaseDiscountPercentage]         NUMERIC (19, 6) NULL,
    [Creationtime]                   INT             NULL,
    [UpdateTime]                     INT             NULL,
    [FixedAssetValueDate]            DATETIME        NULL,
    [GrossProfitBaseMethod]          SMALLINT        NULL,
    [BaseDocumentType]               INT             NULL,
    [BaseDocumentInternalID]         INT             NULL,
    [RowNumber]                      INT             NULL,
    [TargetDocumentType]             INT             NULL,
    [TargetDocumentInternalID]       INT             NULL,
    [BaseDocumentReference]          NVARCHAR (16)   NULL,
    [BaseRow]                        INT             NULL,
    [RowStatus]                      VARCHAR (1)     NULL,
    [Description]                    NVARCHAR (100)  NULL,
    [RemainingOpenQuantity]          NUMERIC (19, 6) NULL,
    [CurrencyRate]                   NUMERIC (19, 6) NULL,
    [RowTotal]                       NUMERIC (19, 6) NULL,
    [RowTotalForeignCurrency]        NUMERIC (19, 6) NULL,
    [OpenAmount]                     NUMERIC (19, 6) NULL,
    [OpenAmountForeignCurrency]      NUMERIC (19, 6) NULL,
    [WarehouseCode]                  NVARCHAR (8)    NULL,
    [AccountCode]                    NVARCHAR (15)   NULL,
    [GrossProfitBasePrice]           NUMERIC (19, 6) NULL,
    [UnitPrice]                      NUMERIC (19, 6) NULL,
    [CreditMemoAmount]               NUMERIC (19, 6) NULL,
    [BaseBusinessPartnerCode]        NVARCHAR (15)   NULL,
    [DistributionRule]               NVARCHAR (8)    NULL,
    [TaxDefinition]                  NVARCHAR (8)    NULL,
    [GrossPrice]                     NUMERIC (19, 6) NULL,
    [PackingQuantity]                NUMERIC (19, 6) NULL,
    [BaseDocumentNumber]             INT             NULL,
    [BusinessPartnerBaseDocument]    NVARCHAR (100)  NULL,
    [AdditionalIdentifier]           NVARCHAR (16)   NULL,
    [RowGrossProfit]                 NUMERIC (19, 6) NULL,
    [VisualOrder]                    INT             NULL,
    [ItemLastSalesPrice]             NUMERIC (19, 6) NULL,
    [BaseQuantity]                   NUMERIC (19, 6) NULL,
    [BaseOpenQuantity]               NUMERIC (19, 6) NULL,
    [Unit]                           NVARCHAR (100)  NULL,
    [UnitOfMeasurement]              NUMERIC (19, 6) NULL,
    [ItemCost]                       NUMERIC (19, 6) NULL,
    [ShipToDescription]              NVARCHAR (254)  NULL,
    [TotalCalculationPrice]          VARCHAR (1)     NULL,
    [GrossTotal]                     NUMERIC (19, 6) NULL,
    [GrossTotalForeignCurrency]      NUMERIC (19, 6) NULL,
    [DistributeFreight]              VARCHAR (1)     NULL,
    [DetailsOverWritten]             VARCHAR (1)     NULL,
    [COGSDistributionRuleCode]       NVARCHAR (8)    NULL,
    [COGSAccountCode]                NVARCHAR (15)   NULL,
    [ActualDeliveryDate]             DATETIME        NULL,
    [DepartmentCode]                 NVARCHAR (8)    NULL,
    [LocationCode]                   NVARCHAR (8)    NULL,
    [COGSDistributionRuleCode2]      NVARCHAR (8)    NULL,
    [COGSDistributionRuleCode3]      NVARCHAR (8)    NULL,
    [TotalCostOfGoodsValue]          NUMERIC (19, 6) NULL,
    [TotalBasePriceForProfit]        NUMERIC (19, 6) NULL,
    [UOMIfBaseUnit]                  NVARCHAR (100)  NULL,
    [UOMValueIfBaseUnit]             NUMERIC (19, 6) NULL,
    [VATGroupSource]                 VARCHAR (1)     NULL,
    [WithoutInventoryMovement]       VARCHAR (1)     NULL,
    [UnitOfMeasurementEntry]         INT             NULL,
    [UOMEntryIfBaseUnit]             INT             NULL,
    [UnitOfMeasurementCode]          NVARCHAR (20)   NULL,
    [UOMCodeifBaseEntry]             NVARCHAR (20)   NULL,
    [InventoryQuantity]              NUMERIC (19, 6) NULL,
    [OpenQuantity]                   NUMERIC (19, 6) NULL,
    [TotalDiscountUSD]               NUMERIC (19, 6) NULL,
    [DocumentTotalUSD]               NUMERIC (19, 6) NULL,
    [PaidUSD]                        NUMERIC (19, 6) NULL,
    [GrossProfitUSD]                 NUMERIC (19, 6) NULL,
    [DownPaymentAmountUSD]           NUMERIC (19, 6) NULL,
    [TotalPaidsumUSD]                NUMERIC (19, 6) NULL,
    [RowTotalUSD]                    NUMERIC (19, 6) NULL,
    [OpenAmountUSD]                  NUMERIC (19, 6) NULL,
    [RowGrossProfitUSD]              NUMERIC (19, 6) NULL,
    [StockSumUSD]                    NUMERIC (19, 6) NULL,
    [GrossTotalUSD]                  NUMERIC (19, 6) NULL,
    [CurrencyID]                     INT             NULL,
    [CountryID]                      INT             NULL,
    [LocationID]                     INT             NULL,
    [DepartmentID]                   INT             NULL,
    [VendorID]                       INT             NULL,
    [DueDateID]                      INT             NULL,
    [CreateDateID]                   INT             NULL,
    [ItemID]                         INT             NULL,
    [DocDateID]                      INT             NULL,
    [DocumentDateID]                 INT             NULL,
    [TaxDateID]                      INT             NULL,
    [UpdateDateID]                   INT             NULL,
    [ActualDeliveryDateID]           INT             NULL,
    [FixedAssetValueDateID]          INT             NULL,
    [ShipDateID]                     INT             NULL,
    [DocumentDueDateID]              INT             NULL,
    [BusinessPartnerID]              INT             NULL
);

