CREATE TABLE [dbo].[CancelledExpensesAudit] (
    [ExpenseId]             INT             NULL,
    [Approver]              NVARCHAR (MAX)  NULL,
    [Description]           NVARCHAR (MAX)  NULL,
    [ExpenseDate]           DATETIME2 (7)   NULL,
    [Quantity]              INT             NULL,
    [UnitPrice]             NUMERIC (18, 2) NULL,
    [ApplicationUserid]     NVARCHAR (450)  NULL,
    [CountryId]             INT             NULL,
    [CurrencyId]            INT             NULL,
    [ExpenseCodeId]         INT             NULL,
    [DocumentTypeId]        INT             NULL,
    [LocationId]            INT             NULL,
    [DepartmentId]          INT             NULL,
    [ProjectId]             INT             NULL,
    [StaffLevelId]          INT             NULL,
    [USDCost]               NUMERIC (18, 2) NULL,
    [Comments]              NVARCHAR (MAX)  NULL,
    [CreatedDate]           DATETIME2 (7)   NULL,
    [BankAccountId]         INT             NULL,
    [MobilePaymentId]       INT             NULL,
    [PaymentBatchHistoryId] INT             NULL,
    [PaymentBatchId]        INT             NULL,
    [CashAdvance]           BIT             NULL,
    [PaymentNumber]         INT             NULL,
    [SapJournalEntryNumber] INT             NULL,
    [CasualCarrierId]       INT             NULL,
    [CasualName]            NVARCHAR (MAX)  NULL,
    [CasualPhoneNumber]     NVARCHAR (MAX)  NULL,
    [JobGradeId]            INT             NULL,
    [ExpenseHeaderId]       INT             NULL,
    [CasualWorkerId]        INT             NULL,
    [StatusId]              INT             NULL,
    [CasualActivityId]      INT             NULL,
    [EmployeeId]            INT             NULL,
    [TotalCost]             NUMERIC (29, 2) NULL
);

