CREATE TABLE [dbo].[DocsForConfirmation] (
    [InternalNumber]        INT            NULL,
    [Draft]                 VARCHAR (1)    NULL,
    [DocumentEntry]         INT            NULL,
    [CreateDate]            DATETIME       NULL,
    [ObjectType]            NVARCHAR (20)  NULL,
    [AuthorizationTemplate] INT            NULL,
    [CountryCode]           NVARCHAR (3)   NULL,
    [OwnerID]               INT            NULL,
    [Status]                VARCHAR (1)    NULL,
    [Remarks]               NVARCHAR (254) NULL,
    [CreateTime]            SMALLINT       NULL,
    [SrcDocEnt]             INT            NULL,
    [DraftType]             NVARCHAR (20)  NULL,
    [DraftEntry]            INT            NULL,
    [BFType]                VARCHAR (1)    NULL,
    [ProcessID]             INT            NULL,
    [ProcesStat]            VARCHAR (1)    NULL,
    [StpUpdated]            VARCHAR (1)    NULL,
    [UserID]                INT            NULL,
    [UpdateDate]            DATETIME       NULL,
    [UpdateTime]            SMALLINT       NULL,
    [SortId]                SMALLINT       NULL,
    [DocumentDate]          DATETIME       NULL,
    [StageCode]             INT            NULL,
    [NOofAuthorizors]       SMALLINT       NULL,
    [NOofRejects]           SMALLINT       NULL,
    [UserSignature]         SMALLINT       NULL,
    [StageKey]              INT            NULL,
    [ApprovalType]          NVARCHAR (100) NULL
);

