CREATE TABLE [dbo].[Expense] (
    [ExpenseId]             INT             NULL,
    [Description]           NVARCHAR (MAX)  NULL,
    [Quantity]              INT             NULL,
    [UnitPrice]             DECIMAL (18, 2) NULL,
    [TotalCost]             DECIMAL (18, 2) NULL,
    [USDCost]               DECIMAL (18, 2) NULL,
    [Comments]              NVARCHAR (MAX)  NULL,
    [PaymentBatchHistoryId] INT             NULL,
    [PaymentBatchId]        INT             NULL,
    [CashAdvance]           BIT             NULL,
    [PaymentNumber]         INT             NULL,
    [SapJournalEntryNumber] INT             NULL,
    [CountryCode]           NVARCHAR (MAX)  NOT NULL,
    [CountryName]           NVARCHAR (MAX)  NULL,
    [DepartmentCode]        NVARCHAR (MAX)  NULL,
    [DepartmentName]        NVARCHAR (MAX)  NULL,
    [LocationCode]          NVARCHAR (MAX)  NULL,
    [LocationName]          NVARCHAR (MAX)  NULL,
    [CurrencyCode]          NVARCHAR (MAX)  NULL,
    [StaffLevelName]        NVARCHAR (MAX)  NULL,
    [ExpenseCodeName]       NVARCHAR (MAX)  NULL,
    [ExpenseCodeValue]      INT             NULL,
    [ExpenseTypeName]       NVARCHAR (MAX)  NULL,
    [ExpenseMonth]          INT             NULL,
    [ExpenseYear]           INT             NULL,
    [FullName]              NVARCHAR (MAX)  NULL,
    [Approver]              NVARCHAR (MAX)  NULL,
    [Status]                NVARCHAR (MAX)  NULL,
    [ExpenseDate]           DATETIME2 (7)   NULL,
    [CreateDate]            DATETIME2 (7)   NULL,
    [Email]                 NVARCHAR (256)  NULL,
    [DefaultApproverName]   NVARCHAR (MAX)  NULL,
    [DefaultApproverEmail]  NVARCHAR (MAX)  NULL,
    [ExpenseDateKey]        INT             NULL,
    [CreateDateKey]         INT             NULL,
    [CountryId]             INT             NULL,
    [DepartmentId]          INT             NULL,
    [LocationId]            INT             NULL,
    [ExpenseCodeId]         INT             NULL,
    [ExpenseTypeId]         INT             NULL,
    [StaffLevelId]          INT             NULL,
    [ApplicationUserId]     NVARCHAR (450)  NULL,
    [StatusId]              INT             NULL,
    [ProjectId]             INT             NULL,
    [CasualActivityId]      INT             NULL,
    [JobGradeId]            INT             NULL,
    [ExpenseHeaderID]       INT             NULL,
    [MobilePaymentID]       INT             NULL,
    [BankAccountID]         INT             NULL,
    [EmployeeID]            INT             NULL,
    [CasualWorkerID]        INT             NULL
);


GO
CREATE NONCLUSTERED INDEX [EXP_IDX1]
    ON [dbo].[Expense]([ExpenseDate] ASC)
    INCLUDE([ExpenseId], [Description], [TotalCost], [USDCost], [PaymentNumber], [SapJournalEntryNumber], [Approver], [CreateDate], [CountryId], [DepartmentId], [LocationId], [ExpenseTypeId], [ApplicationUserId], [StatusId], [ProjectId], [CasualActivityId], [JobGradeId], [ExpenseHeaderID], [MobilePaymentID], [BankAccountID], [EmployeeID], [CasualWorkerID]);

