CREATE TABLE [dbo].[GoodsReceipts] (
    [Comments]                NVARCHAR (254)  NULL,
    [UpdateDate]              DATETIME        NULL,
    [CreateDate]              DATETIME        NULL,
    [Series]                  INT             NULL,
    [TaxDate]                 DATETIME        NULL,
    [U_VENDOR_ACCPT]          NVARCHAR (10)   NULL,
    [Project]                 NVARCHAR (20)   NULL,
    [ItemCode]                NVARCHAR (50)   NULL,
    [Quantity]                NUMERIC (19, 6) NULL,
    [Price]                   NUMERIC (19, 6) NULL,
    [Currency]                NVARCHAR (3)    NULL,
    [Rate]                    NUMERIC (19, 6) NULL,
    [StockPrice]              NUMERIC (19, 6) NULL,
    [StockSum]                NUMERIC (19, 6) NULL,
    [unitMsr2]                NVARCHAR (100)  NULL,
    [UomEntry]                INT             NULL,
    [UomCode]                 NVARCHAR (20)   NULL,
    [CountryCode]             NVARCHAR (3)    NULL,
    [Text]                    NVARCHAR (MAX)  NULL,
    [DocumentEntry]           INT             NULL,
    [DocumentNumber]          INT             NULL,
    [DocumentDate]            DATETIME        NULL,
    [DueDate]                 DATETIME        NULL,
    [DocumentCurrency]        NVARCHAR (3)    NULL,
    [DocumentTotal]           NUMERIC (19, 6) NULL,
    [Reference1]              NVARCHAR (11)   NULL,
    [Reference2]              NVARCHAR (11)   NULL,
    [JournalRemarks]          NVARCHAR (50)   NULL,
    [TransactionNumber]       INT             NULL,
    [PriceList]               SMALLINT        NULL,
    [GenerationTime]          SMALLINT        NULL,
    [SalesEmployee]           INT             NULL,
    [SystemPrice]             NUMERIC (19, 6) NULL,
    [DocumentTotalUSD]        NUMERIC (19, 6) NULL,
    [PostingPeriod]           INT             NULL,
    [UserSignature]           SMALLINT        NULL,
    [UserSignature2]          SMALLINT        NULL,
    [DocumentDraftInternalID] INT             NULL,
    [WorkStationID]           INT             NULL,
    [MAX1099Amount]           NUMERIC (19, 6) NULL,
    [VersionNumber]           NVARCHAR (11)   NULL,
    [AttachmentEntry]         INT             NULL,
    [CreateTime]              INT             NULL,
    [UpdateTime]              INT             NULL,
    [U_TRSR_COUNTRY]          NVARCHAR (10)   NULL,
    [U_WHR]                   NVARCHAR (30)   NULL,
    [U_Request_ID]            NVARCHAR (50)   NULL,
    [DiscountPercentage]      NUMERIC (19, 6) NULL,
    [RowNumber]               INT             NULL,
    [Description]             NVARCHAR (100)  NULL,
    [RemainingOpenQuantity]   NUMERIC (19, 6) NULL,
    [RowTotal]                NUMERIC (19, 6) NULL,
    [OpenAmount]              NUMERIC (19, 6) NULL,
    [WarehouseCode]           NVARCHAR (8)    NULL,
    [AccountCode]             NVARCHAR (15)   NULL,
    [UnitPrice]               NUMERIC (19, 6) NULL,
    [CreditMemoAmount]        NUMERIC (19, 6) NULL,
    [RowTotalUSD]             NUMERIC (19, 6) NULL,
    [OpenAmountUSD]           NUMERIC (19, 6) NULL,
    [DistributionRule]        NVARCHAR (8)    NULL,
    [VisualOrder]             INT             NULL,
    [ItemLastSalesPrice]      NUMERIC (19, 6) NULL,
    [Unit]                    NVARCHAR (100)  NULL,
    [GrossPrice]              NUMERIC (19, 6) NULL,
    [AdditionalIdentifier]    NVARCHAR (16)   NULL,
    [DescriptionOverwritten]  VARCHAR (1)     NULL,
    [StockSumUSD]             NUMERIC (19, 6) NULL,
    [DepartmentCode]          NVARCHAR (8)    NULL,
    [LocationCode]            NVARCHAR (8)    NULL,
    [UOMEntryBaseUnit]        INT             NULL,
    [UOMCodeBaseUnit]         NVARCHAR (20)   NULL,
    [InventoryQuantity]       NUMERIC (19, 6) NULL,
    [OpenInventoryQuantity]   NUMERIC (19, 6) NULL,
    [PriceEdited]             VARCHAR (1)     NULL,
    [U_TRGT_PRICE]            NUMERIC (19, 6) NULL,
    [RowTotalForeignCurrency] NUMERIC (19, 6) NULL,
    [CountryID]               INT             NULL,
    [CurrencyID]              INT             NULL,
    [DueDateID]               INT             NULL,
    [DocumentDateID]          INT             NULL,
    [DepartmentID]            INT             NULL,
    [LocationID]              INT             NULL,
    [ItemID]                  INT             NULL,
    [CreateDateID]            INT             NULL,
    [UpdateDateID]            INT             NULL,
    [TaxDateID]               INT             NULL,
    [DocumentSubmissionDate]  DATETIME        NULL,
    [U_Season]                NVARCHAR (10)   NULL,
    [U_Requestor]             NVARCHAR (50)   NULL,
    [U_WebPRID]               INT             NULL
);

