CREATE TABLE [dbo].[GoodsReceiptPO] (
    [U_TRSR_COUNTRY]              NVARCHAR (10)   NULL,
    [quantity]                    NUMERIC (19, 6) NULL,
    [CountryCode]                 NVARCHAR (10)   NULL,
    [createdate]                  DATETIME        NULL,
    [DepartmentCode]              NVARCHAR (8)    NULL,
    [LocationCode]                NVARCHAR (8)    NULL,
    [ItemCode]                    NVARCHAR (50)   NULL,
    [Comments]                    NVARCHAR (254)  NULL,
    [Currency]                    NVARCHAR (3)    NULL,
    [Text]                        NVARCHAR (MAX)  NULL,
    [U_CusotmerSat]               NVARCHAR (20)   NULL,
    [U_CusotmerSat2]              NVARCHAR (20)   NULL,
    [DocumentEntry]               INT             NULL,
    [DocumentNumber]              INT             NULL,
    [Canceled]                    VARCHAR (1)     NULL,
    [DocumentDate]                DATETIME        NULL,
    [BusinessPartnerCode]         NVARCHAR (15)   NULL,
    [BusinessPartnerName]         NVARCHAR (100)  NULL,
    [TransactionID]               INT             NULL,
    [UserSignature]               SMALLINT        NULL,
    [DocumentOwner]               INT             NULL,
    [CustomerSatisfaction]        NVARCHAR (50)   NULL,
    [DocumentStatus]              VARCHAR (1)     NULL,
    [DocumentClosedManually]      VARCHAR (1)     NULL,
    [ControlAccount]              NVARCHAR (15)   NULL,
    [AttachmentEntry]             INT             NULL,
    [PaidForeignCurrency]         NUMERIC (19, 6) NULL,
    [PaidtoDate]                  NUMERIC (19, 6) NULL,
    [TaxDate]                     DATETIME        NULL,
    [SalesEmployee]               INT             NULL,
    [AccountCode]                 NVARCHAR (15)   NULL,
    [Description]                 NVARCHAR (100)  NULL,
    [RowTotal]                    NUMERIC (19, 6) NULL,
    [RowStatus]                   VARCHAR (1)     NULL,
    [TotalForeignCurrency]        NUMERIC (19, 6) NULL,
    [TargetDocumentEntry]         INT             NULL,
    [PurQuotationRequiredDate]    DATETIME        NULL,
    [TotalSumUSD]                 NUMERIC (19, 6) NULL,
    [BaseDocumentType]            INT             NULL,
    [BaseDocumentReference]       NVARCHAR (16)   NULL,
    [BaseDocumentRow]             INT             NULL,
    [RowNumber]                   INT             NULL,
    [Requestor]                   NVARCHAR (50)   NULL,
    [TargetDocumentType]          INT             NULL,
    [CountryID]                   INT             NULL,
    [VendorID]                    INT             NULL,
    [ItemID]                      INT             NULL,
    [DocumentDateID]              INT             NULL,
    [CreateDateID]                INT             NULL,
    [DepartmentID]                INT             NULL,
    [LocationID]                  INT             NULL,
    [CurrencyID]                  INT             NULL,
    [UpdateDate]                  DATETIME        NULL,
    [TaxDateID]                   INT             NULL,
    [UpdateDateID]                INT             NULL,
    [U_Requestor]                 NVARCHAR (50)   NULL,
    [Price]                       NUMERIC (19, 6) NULL,
    [DocumentTotalSystemCurrency] NUMERIC (19, 6) NULL,
    [TaxAmountSystemCurrency]     NUMERIC (19, 6) NULL,
    [U_U_DP_DATE]                 DATETIME        NULL,
    [U_WebProcNumber]             INT             NULL,
    [U_WebPRID]                   INT             NULL,
    [U_Purchaser]                 NVARCHAR (30)   NULL,
    [U_Season]                    NVARCHAR (50)   NULL,
    [U_InputsApprover]            NVARCHAR (3)    NULL,
    [BaseDocumentEntry]           INT             NULL,
    [VatGroup]                    NVARCHAR (8)    NULL,
    [GrossTotal]                  NUMERIC (19, 6) NULL,
    [GrossTotalForeignCurrency]   NUMERIC (19, 6) NULL,
    [PriceAfVAT]                  NUMERIC (19, 6) NULL,
    [VATSum]                      NUMERIC (19, 6) NULL,
    [VatSumFrgn]                  NUMERIC (19, 6) NULL,
    [WarehouseID]                 NVARCHAR (8)    NULL,
    [DocumentDraftInternalID]     INT             NULL,
    [DocumentSubmissionDate]      DATETIME        NULL,
    [CreateTime]                  INT             NULL,
    [UserSignature2]              SMALLINT        NULL,
    [UpdateTime]                  INT             NULL,
    [Truck Reg ID]                NVARCHAR (30)   NULL,
    [Truck Driver Contact]        NVARCHAR (30)   NULL,
    [DeliveryDate]                DATETIME        NULL,
    [UOMCode]                     NVARCHAR (20)   NULL
);

