CREATE TABLE [dbo].[OACT] (
    [AcctCode]      NVARCHAR (15)   NOT NULL,
    [AcctName]      NVARCHAR (100)  NULL,
    [CurrTotal]     NUMERIC (19, 6) NULL,
    [Finanse]       CHAR (1)        NULL,
    [Postable]      CHAR (1)        NULL,
    [Levels]        SMALLINT        NULL,
    [GrpLine]       INT             NULL,
    [FatherNum]     NVARCHAR (15)   NULL,
    [AccntntCod]    NVARCHAR (15)   NULL,
    [ActCurr]       NVARCHAR (3)    NULL,
    [SysTotal]      NUMERIC (19, 6) NULL,
    [FcTotal]       NUMERIC (19, 6) NULL,
    [CreateDate]    DATETIME        NULL,
    [UpdateDate]    DATETIME        NULL,
    [DataSource]    CHAR (1)        NULL,
    [UserSign]      SMALLINT        NULL,
    [ValidFor]      CHAR (1)        NULL,
    [FrozenFor]     CHAR (1)        NULL,
    [FrozenFrom]    DATETIME        NULL,
    [Counter]       INT             NULL,
    [FormatCode]    NVARCHAR (210)  NULL,
    [CfwRlvnt]      CHAR (1)        NULL,
    [UserSign2]     SMALLINT        NULL,
    [PrjRelvnt]     CHAR (1)        NULL,
    [ActId]         NVARCHAR (210)  NOT NULL,
    [U_CodeSubType] NVARCHAR (100)  NULL,
    [U_CodeType]    NVARCHAR (100)  NULL,
    [ValidTo]       DATETIME        NULL,
    [ValidFrom]     DATETIME        NULL,
    [CountryCode]   NVARCHAR (10)   NULL
);

