CREATE TABLE [dbo].[OCRD] (
    [CardCode]              NVARCHAR (15)   NOT NULL,
    [CardName]              NVARCHAR (100)  NULL,
    [CardType]              CHAR (1)        NULL,
    [GroupCode]             SMALLINT        NULL,
    [CmpPrivate]            CHAR (1)        NULL,
    [Address]               NVARCHAR (100)  NULL,
    [MailAddres]            NVARCHAR (100)  NULL,
    [Phone1]                NVARCHAR (20)   NULL,
    [Phone2]                NVARCHAR (20)   NULL,
    [Fax]                   NVARCHAR (20)   NULL,
    [CntctPrsn]             NVARCHAR (90)   NULL,
    [Notes]                 NVARCHAR (100)  NULL,
    [Balance]               NUMERIC (19, 6) NULL,
    [ChecksBal]             NUMERIC (19, 6) NULL,
    [DNotesBal]             NUMERIC (19, 6) NULL,
    [OrdersBal]             NUMERIC (19, 6) NULL,
    [GroupNum]              SMALLINT        NULL,
    [CreditLine]            NUMERIC (19, 6) NULL,
    [DebtLine]              NUMERIC (19, 6) NULL,
    [VatStatus]             CHAR (1)        NULL,
    [LicTradNum]            NVARCHAR (32)   NULL,
    [DdctStatus]            CHAR (1)        NULL,
    [DdctPrcnt]             NUMERIC (19, 6) NULL,
    [ListNum]               SMALLINT        NULL,
    [DNoteBalFC]            NUMERIC (19, 6) NULL,
    [OrderBalFC]            NUMERIC (19, 6) NULL,
    [DNoteBalSy]            NUMERIC (19, 6) NULL,
    [OrderBalSy]            NUMERIC (19, 6) NULL,
    [IntrstRate]            NUMERIC (19, 6) NULL,
    [CommGrCode]            SMALLINT        NULL,
    [Free_Text]             NTEXT           NULL,
    [SlpCode]               INT             NULL,
    [Currency]              NVARCHAR (3)    NULL,
    [BalanceSys]            NUMERIC (19, 6) NULL,
    [BalanceFC]             NUMERIC (19, 6) NULL,
    [Cellular]              NVARCHAR (50)   NULL,
    [City]                  NVARCHAR (100)  NULL,
    [County]                NVARCHAR (100)  NULL,
    [Country]               NVARCHAR (3)    NULL,
    [MailCity]              NVARCHAR (100)  NULL,
    [MailCounty]            NVARCHAR (100)  NULL,
    [MailCountr]            NVARCHAR (3)    NULL,
    [E_Mail]                NVARCHAR (100)  NULL,
    [DflAccount]            NVARCHAR (50)   NULL,
    [DflBranch]             NVARCHAR (50)   NULL,
    [BankCode]              NVARCHAR (30)   NULL,
    [AddID]                 NVARCHAR (64)   NULL,
    [CardFName]             NVARCHAR (100)  NULL,
    [FatherType]            CHAR (1)        NULL,
    [CreateDate]            DATETIME        NULL,
    [UpdateDate]            DATETIME        NULL,
    [MinIntrst]             NUMERIC (19, 6) NULL,
    [DataSource]            CHAR (1)        NULL,
    [ExemptNo]              NVARCHAR (50)   NULL,
    [Priority]              INT             NULL,
    [CreditCard]            SMALLINT        NULL,
    [CrCardNum]             NVARCHAR (64)   NULL,
    [UserSign]              SMALLINT        NULL,
    [LocMth]                CHAR (1)        NULL,
    [validFor]              CHAR (1)        NULL,
    [validFrom]             DATETIME        NULL,
    [validTo]               DATETIME        NULL,
    [frozenFor]             CHAR (1)        NULL,
    [DdgKey]                INT             NULL,
    [DdtKey]                INT             NULL,
    [ValidComm]             NVARCHAR (30)   NULL,
    [FrozenComm]            NVARCHAR (30)   NULL,
    [DiscInRet]             CHAR (1)        NULL,
    [State1]                NVARCHAR (3)    NULL,
    [State2]                NVARCHAR (3)    NULL,
    [LogInstanc]            INT             NULL,
    [ObjType]               NVARCHAR (20)   NULL,
    [Indicator]             NVARCHAR (2)    NULL,
    [ShipType]              SMALLINT        NULL,
    [DebPayAcct]            NVARCHAR (15)   NULL,
    [ShipToDef]             NVARCHAR (50)   NULL,
    [Block]                 NVARCHAR (100)  NULL,
    [MailBlock]             NVARCHAR (100)  NULL,
    [DocEntry]              INT             NOT NULL,
    [FormCode]              INT             NULL,
    [PymCode]               NVARCHAR (15)   NULL,
    [BackOrder]             CHAR (1)        NULL,
    [PartDelivr]            CHAR (1)        NULL,
    [BankCountr]            NVARCHAR (3)    NULL,
    [CollecAuth]            CHAR (1)        NULL,
    [PyBlckDesc]            INT             NULL,
    [HousBnkCry]            NVARCHAR (3)    NULL,
    [ProjectCod]            NVARCHAR (20)   NULL,
    [SysMatchNo]            INT             NULL,
    [VatIdUnCmp]            NVARCHAR (32)   NULL,
    [AgentCode]             NVARCHAR (32)   NULL,
    [TolrncDays]            SMALLINT        NULL,
    [DeferrTax]             CHAR (1)        NULL,
    [MaxAmount]             NUMERIC (19, 6) NULL,
    [ToDate]                DATETIME        NULL,
    [WTLiable]              CHAR (1)        NULL,
    [TypWTReprt]            CHAR (1)        NULL,
    [VATRegNum]             NVARCHAR (32)   NULL,
    [Industry]              NTEXT           NULL,
    [Business]              NTEXT           NULL,
    [IsDomestic]            CHAR (1)        NULL,
    [IsResident]            CHAR (1)        NULL,
    [AutoCalBCG]            CHAR (1)        NULL,
    [OtrCtlAcct]            NVARCHAR (15)   NULL,
    [AliasName]             NTEXT           NULL,
    [BoEPrsnt]              NVARCHAR (15)   NULL,
    [ITWTCode]              NVARCHAR (4)    NULL,
    [BillToDef]             NVARCHAR (50)   NULL,
    [DpmClear]              NVARCHAR (15)   NULL,
    [IntrntSite]            NVARCHAR (100)  NULL,
    [LangCode]              INT             NULL,
    [HousActKey]            INT             NULL,
    [Profession]            NVARCHAR (50)   NULL,
    [DflBankKey]            INT             NULL,
    [BCACode]               NVARCHAR (3)    NULL,
    [VerifNum]              NVARCHAR (32)   NULL,
    [BankCtlKey]            NVARCHAR (2)    NULL,
    [AddrType]              NVARCHAR (100)  NULL,
    [InsurOp347]            CHAR (1)        NULL,
    [MailAddrTy]            NVARCHAR (100)  NULL,
    [StreetNo]              NVARCHAR (100)  NULL,
    [TaxRndRule]            CHAR (1)        NULL,
    [OpCode347]             CHAR (1)        NULL,
    [DpmIntAct]             NVARCHAR (15)   NULL,
    [ResidenNum]            CHAR (1)        NULL,
    [UserSign2]             SMALLINT        NULL,
    [Affiliate]             CHAR (1)        NULL,
    [MivzExpSts]            CHAR (1)        NULL,
    [HierchDdct]            CHAR (1)        NULL,
    [CertWHT]               CHAR (1)        NULL,
    [WHShaamGrp]            CHAR (1)        NULL,
    [IndustryC]             INT             NULL,
    [DatevAcct]             INT             NULL,
    [DatevFirst]            CHAR (1)        NULL,
    [GTSRegNum]             NVARCHAR (20)   NULL,
    [DflSwift]              NVARCHAR (50)   NULL,
    [DflIBAN]               NVARCHAR (50)   NULL,
    [Series]                SMALLINT        NULL,
    [Number]                INT             NULL,
    [TaxIdIdent]            CHAR (1)        NULL,
    [Attachment]            NTEXT           NULL,
    [AtcEntry]              INT             NULL,
    [DiscRel]               CHAR (1)        NULL,
    [SCAdjust]              CHAR (1)        NULL,
    [GlblLocNum]            NVARCHAR (50)   NULL,
    [MandateID]             NVARCHAR (35)   NULL,
    [CountryCode]           NVARCHAR (20)   NULL,
    [U_Approval]            NVARCHAR (15)   NULL,
    [VATRegistrationNumber] NVARCHAR (9)    NULL
);

