CREATE TABLE [dbo].[OITB] (
    [ItmsGrpCod]  SMALLINT        NOT NULL,
    [ItmsGrpNam]  NVARCHAR (20)   NOT NULL,
    [Locked]      CHAR (1)        NULL,
    [DataSource]  CHAR (1)        NULL,
    [UserSign]    SMALLINT        NULL,
    [BalInvntAc]  NVARCHAR (15)   NULL,
    [SaleCostAc]  NVARCHAR (15)   NULL,
    [TransferAc]  NVARCHAR (15)   NULL,
    [RevenuesAc]  NVARCHAR (15)   NULL,
    [VarianceAc]  NVARCHAR (15)   NULL,
    [DecreasAc]   NVARCHAR (15)   NULL,
    [IncreasAc]   NVARCHAR (15)   NULL,
    [ReturnAc]    NVARCHAR (15)   NULL,
    [ExpensesAc]  NVARCHAR (15)   NULL,
    [EURevenuAc]  NVARCHAR (15)   NULL,
    [EUExpensAc]  NVARCHAR (15)   NULL,
    [FrRevenuAc]  NVARCHAR (15)   NULL,
    [FrExpensAc]  NVARCHAR (15)   NULL,
    [ExmptIncom]  NVARCHAR (15)   NULL,
    [Alert]       CHAR (1)        NULL,
    [PriceDifAc]  NVARCHAR (15)   NULL,
    [ExchangeAc]  NVARCHAR (15)   NULL,
    [BalanceAcc]  NVARCHAR (15)   NULL,
    [PurchaseAc]  NVARCHAR (15)   NULL,
    [PAReturnAc]  NVARCHAR (15)   NULL,
    [PurchOfsAc]  NVARCHAR (15)   NULL,
    [ShpdGdsAct]  NVARCHAR (15)   NULL,
    [VatRevAct]   NVARCHAR (15)   NULL,
    [DecresGlAc]  NVARCHAR (15)   NULL,
    [IncresGlAc]  NVARCHAR (15)   NULL,
    [InvntSys]    CHAR (1)        NULL,
    [PlaningSys]  CHAR (1)        NULL,
    [PrcrmntMtd]  CHAR (1)        NULL,
    [OrdrMulti]   NUMERIC (19, 6) NULL,
    [MinOrdrQty]  NUMERIC (19, 6) NULL,
    [WipAcct]     NVARCHAR (15)   NULL,
    [WipVarAcct]  NVARCHAR (15)   NULL,
    [ExpClrAct]   NVARCHAR (15)   NULL,
    [Object]      NVARCHAR (20)   NULL,
    [createDate]  DATETIME        NULL,
    [userSign2]   SMALLINT        NULL,
    [updateDate]  DATETIME        NULL,
    [ARCMAct]     NVARCHAR (15)   NULL,
    [ARCMFrnAct]  NVARCHAR (15)   NULL,
    [ARCMEUAct]   NVARCHAR (15)   NULL,
    [APCMAct]     NVARCHAR (15)   NULL,
    [APCMFrnAct]  NVARCHAR (15)   NULL,
    [APCMEUAct]   NVARCHAR (15)   NULL,
    [ItemClass]   CHAR (1)        NULL,
    [OSvcCode]    INT             NULL,
    [ISvcCode]    INT             NULL,
    [ServiceGrp]  INT             NULL,
    [NCMCode]     INT             NULL,
    [MatType]     NVARCHAR (3)    NULL,
    [MatGrp]      INT             NULL,
    [ProductSrc]  NVARCHAR (2)    NULL,
    [NegStckAct]  NVARCHAR (15)   NULL,
    [StkInTnAct]  NVARCHAR (15)   NULL,
    [UgpEntry]    INT             NULL,
    [CountryCode] NVARCHAR (10)   NULL
);

