CREATE TABLE [dbo].[OITM] (
    [ItemName]          NVARCHAR (100)  NULL,
    [FrgnName]          NVARCHAR (100)  NULL,
    [ItmsGrpCod]        SMALLINT        NULL,
    [VatGourpSa]        NVARCHAR (8)    NULL,
    [SellItem]          CHAR (1)        NULL,
    [InvntItem]         CHAR (1)        NULL,
    [OnHand]            NUMERIC (19, 6) NULL,
    [IsCommited]        NUMERIC (19, 6) NULL,
    [OnOrder]           NUMERIC (19, 6) NULL,
    [MaxLevel]          NUMERIC (19, 6) NULL,
    [DfltWH]            NVARCHAR (8)    NULL,
    [BuyUnitMsr]        NVARCHAR (100)  NULL,
    [SalUnitMsr]        NVARCHAR (100)  NULL,
    [Counted]           NUMERIC (19, 6) NULL,
    [UserSign]          SMALLINT        NULL,
    [CreateDate]        DATETIME        NULL,
    [UpdateDate]        DATETIME        NULL,
    [VatGroupPu]        NVARCHAR (8)    NULL,
    [DocEntry]          INT             NULL,
    [GLMethod]          CHAR (1)        NULL,
    [InvntryUom]        NVARCHAR (100)  NULL,
    [UserSign2]         SMALLINT        NULL,
    [UgpEntry]          INT             NULL,
    [PUoMEntry]         INT             NULL,
    [U_SUB_GR]          NVARCHAR (40)   NULL,
    [U_Item_Visibility] NVARCHAR (10)   NULL,
    [ItemCode]          NVARCHAR (50)   NULL,
    [ValidFor]          CHAR (1)        NULL,
    [ValidFrom]         DATETIME        NULL,
    [ValidTo]           DATETIME        NULL,
    [CountryCode]       NVARCHAR (10)   NULL,
    [AtcEntry]          INT             NULL,
    [PrchseItem]        VARCHAR (3)     NULL,
    [IWeight1]          NUMERIC (19, 6) NULL,
    [U_ExpenseAcc]      NVARCHAR (15)   NULL,
    [PrcrmntMtd]        VARCHAR (1)     NULL,
    [ExpensAcct]        NVARCHAR (15)   NULL,
    [QryGroup1]         VARCHAR (1)     NULL,
    [AssetClass]        NVARCHAR (20)   NULL,
    [CapDate]           DATETIME        NULL,
    [AcqDate]           DATETIME        NULL,
    [Itemtype]          VARCHAR (1)     NULL,
    [DataSource]        VARCHAR (1)     NULL
);

