CREATE TABLE [dbo].[OITW] (
    [ItemCode]    NVARCHAR (50)   NOT NULL,
    [WhsCode]     NVARCHAR (8)    NOT NULL,
    [OnHand]      NUMERIC (19, 6) NULL,
    [IsCommited]  NUMERIC (19, 6) NULL,
    [OnOrder]     NUMERIC (19, 6) NULL,
    [Consig]      NUMERIC (19, 6) NULL,
    [Counted]     NUMERIC (19, 6) NULL,
    [WasCounted]  CHAR (1)        NULL,
    [UserSign]    SMALLINT        NULL,
    [MinStock]    NUMERIC (19, 6) NULL,
    [AvgPrice]    NUMERIC (19, 6) NULL,
    [Locked]      CHAR (1)        NULL,
    [BalInvntAc]  NVARCHAR (15)   NULL,
    [SaleCostAc]  NVARCHAR (15)   NULL,
    [TransferAc]  NVARCHAR (15)   NULL,
    [RevenuesAc]  NVARCHAR (15)   NULL,
    [VarianceAc]  NVARCHAR (15)   NULL,
    [DecreasAc]   NVARCHAR (15)   NULL,
    [IncreasAc]   NVARCHAR (15)   NULL,
    [ReturnAc]    NVARCHAR (15)   NULL,
    [ExpensesAc]  NVARCHAR (15)   NULL,
    [EURevenuAc]  NVARCHAR (15)   NULL,
    [EUExpensAc]  NVARCHAR (15)   NULL,
    [FrRevenuAc]  NVARCHAR (15)   NULL,
    [FrExpensAc]  NVARCHAR (15)   NULL,
    [PriceDifAc]  NVARCHAR (15)   NULL,
    [ExchangeAc]  NVARCHAR (15)   NULL,
    [BalanceAcc]  NVARCHAR (15)   NULL,
    [PurchaseAc]  NVARCHAR (15)   NULL,
    [PAReturnAc]  NVARCHAR (15)   NULL,
    [PurchOfsAc]  NVARCHAR (15)   NULL,
    [ShpdGdsAct]  NVARCHAR (15)   NULL,
    [StockValue]  NUMERIC (19, 6) NULL,
    [DecresGlAc]  NVARCHAR (15)   NULL,
    [IncresGlAc]  NVARCHAR (15)   NULL,
    [WipAcct]     NVARCHAR (15)   NULL,
    [WipVarAcct]  NVARCHAR (15)   NULL,
    [ExpClrAct]   NVARCHAR (15)   NULL,
    [ExpOfstAct]  NVARCHAR (15)   NULL,
    [Object]      NVARCHAR (20)   NULL,
    [createDate]  DATETIME        NULL,
    [userSign2]   SMALLINT        NULL,
    [updateDate]  DATETIME        NULL,
    [ARCMAct]     NVARCHAR (15)   NULL,
    [ARCMFrnAct]  NVARCHAR (15)   NULL,
    [ARCMEUAct]   NVARCHAR (15)   NULL,
    [APCMAct]     NVARCHAR (15)   NULL,
    [APCMFrnAct]  NVARCHAR (15)   NULL,
    [APCMEUAct]   NVARCHAR (15)   NULL,
    [NegStckAct]  NVARCHAR (15)   NULL,
    [StkInTnAct]  NVARCHAR (15)   NULL,
    [CountryCode] NVARCHAR (10)   NULL
);


GO
CREATE NONCLUSTERED INDEX [OITW_WHSCODE]
    ON [dbo].[OITW]([WhsCode] ASC)
    INCLUDE([ItemCode], [OnHand], [AvgPrice], [CountryCode]);

