CREATE TABLE [dbo].[ORIN] (
    [DocEntry]            INT             NULL,
    [DocNum]              INT             NULL,
    [DocType]             VARCHAR (1)     NULL,
    [CANCELED]            VARCHAR (1)     NULL,
    [Handwrtten]          VARCHAR (1)     NULL,
    [Printed]             VARCHAR (1)     NULL,
    [DocStatus]           VARCHAR (1)     NULL,
    [InvntSttus]          VARCHAR (1)     NULL,
    [Transfered]          VARCHAR (1)     NULL,
    [ObjType]             NVARCHAR (20)   NULL,
    [DocDate]             DATETIME        NULL,
    [DocDueDate]          DATETIME        NULL,
    [CardCode]            NVARCHAR (15)   NULL,
    [CardName]            NVARCHAR (100)  NULL,
    [Address]             NVARCHAR (254)  NULL,
    [NumAtCard]           NVARCHAR (100)  NULL,
    [VatPercent]          NUMERIC (19, 6) NULL,
    [VatSum]              NUMERIC (19, 6) NULL,
    [VatSumFC]            NUMERIC (19, 6) NULL,
    [DiscPrcnt]           NUMERIC (19, 6) NULL,
    [DiscSum]             NUMERIC (19, 6) NULL,
    [DiscSumFC]           NUMERIC (19, 6) NULL,
    [DocCur]              NVARCHAR (3)    NULL,
    [DocRate]             NUMERIC (19, 6) NULL,
    [DocTotal]            NUMERIC (19, 6) NULL,
    [DocTotalFC]          NUMERIC (19, 6) NULL,
    [PaidToDate]          NUMERIC (19, 6) NULL,
    [PaidFC]              NUMERIC (19, 6) NULL,
    [GrosProfit]          NUMERIC (19, 6) NULL,
    [GrosProfFC]          NUMERIC (19, 6) NULL,
    [Ref1]                NVARCHAR (11)   NULL,
    [Ref2]                NVARCHAR (11)   NULL,
    [Comments]            NVARCHAR (254)  NULL,
    [JrnlMemo]            NVARCHAR (50)   NULL,
    [TransId]             INT             NULL,
    [ReceiptNum]          INT             NULL,
    [GroupNum]            SMALLINT        NULL,
    [DocTime]             SMALLINT        NULL,
    [SlpCode]             INT             NULL,
    [TrnspCode]           SMALLINT        NULL,
    [PartSupply]          VARCHAR (1)     NULL,
    [Confirmed]           VARCHAR (1)     NULL,
    [GrossBase]           SMALLINT        NULL,
    [ImportEnt]           INT             NULL,
    [CreateTran]          VARCHAR (1)     NULL,
    [SummryType]          VARCHAR (1)     NULL,
    [UpdInvnt]            VARCHAR (1)     NULL,
    [UpdCardBal]          VARCHAR (1)     NULL,
    [Instance]            SMALLINT        NULL,
    [Flags]               INT             NULL,
    [InvntDirec]          VARCHAR (1)     NULL,
    [CntctCode]           INT             NULL,
    [ShowSCN]             VARCHAR (1)     NULL,
    [FatherCard]          NVARCHAR (15)   NULL,
    [SysRate]             NUMERIC (19, 6) NULL,
    [CurSource]           VARCHAR (1)     NULL,
    [VatSumSy]            NUMERIC (19, 6) NULL,
    [DiscSumSy]           NUMERIC (19, 6) NULL,
    [DocTotalSy]          NUMERIC (19, 6) NULL,
    [PaidSys]             NUMERIC (19, 6) NULL,
    [FatherType]          VARCHAR (1)     NULL,
    [GrosProfSy]          NUMERIC (19, 6) NULL,
    [UpdateDate]          DATETIME        NULL,
    [IsICT]               VARCHAR (1)     NULL,
    [CreateDate]          DATETIME        NULL,
    [Volume]              NUMERIC (19, 6) NULL,
    [VolUnit]             SMALLINT        NULL,
    [Weight]              NUMERIC (19, 6) NULL,
    [WeightUnit]          SMALLINT        NULL,
    [Series]              SMALLINT        NULL,
    [TaxDate]             DATETIME        NULL,
    [Filler]              NVARCHAR (8)    NULL,
    [DataSource]          VARCHAR (1)     NULL,
    [StampNum]            NVARCHAR (16)   NULL,
    [isCrin]              VARCHAR (1)     NULL,
    [FinncPriod]          INT             NULL,
    [UserSign]            SMALLINT        NULL,
    [selfInv]             VARCHAR (1)     NULL,
    [VatPaid]             NUMERIC (19, 6) NULL,
    [VatPaidFC]           NUMERIC (19, 6) NULL,
    [VatPaidSys]          NUMERIC (19, 6) NULL,
    [UserSign2]           SMALLINT        NULL,
    [WddStatus]           VARCHAR (1)     NULL,
    [draftKey]            INT             NULL,
    [TotalExpns]          NUMERIC (19, 6) NULL,
    [TotalExpFC]          NUMERIC (19, 6) NULL,
    [TotalExpSC]          NUMERIC (19, 6) NULL,
    [DunnLevel]           INT             NULL,
    [Address2]            NVARCHAR (254)  NULL,
    [LogInstanc]          INT             NULL,
    [Exported]            VARCHAR (1)     NULL,
    [StationID]           INT             NULL,
    [Indicator]           NVARCHAR (2)    NULL,
    [NetProc]             VARCHAR (1)     NULL,
    [AqcsTax]             NUMERIC (19, 6) NULL,
    [AqcsTaxFC]           NUMERIC (19, 6) NULL,
    [AqcsTaxSC]           NUMERIC (19, 6) NULL,
    [CashDiscPr]          NUMERIC (19, 6) NULL,
    [CashDiscnt]          NUMERIC (19, 6) NULL,
    [CashDiscFC]          NUMERIC (19, 6) NULL,
    [CashDiscSC]          NUMERIC (19, 6) NULL,
    [ShipToCode]          NVARCHAR (50)   NULL,
    [LicTradNum]          NVARCHAR (32)   NULL,
    [PaymentRef]          NVARCHAR (27)   NULL,
    [WTSum]               NUMERIC (19, 6) NULL,
    [WTSumFC]             NUMERIC (19, 6) NULL,
    [WTSumSC]             NUMERIC (19, 6) NULL,
    [RoundDif]            NUMERIC (19, 6) NULL,
    [RoundDifFC]          NUMERIC (19, 6) NULL,
    [RoundDifSy]          NUMERIC (19, 6) NULL,
    [CheckDigit]          VARCHAR (1)     NULL,
    [Form1099]            INT             NULL,
    [Box1099]             NVARCHAR (20)   NULL,
    [submitted]           VARCHAR (1)     NULL,
    [PoPrss]              VARCHAR (1)     NULL,
    [Rounding]            VARCHAR (1)     NULL,
    [RevisionPo]          VARCHAR (1)     NULL,
    [Segment]             SMALLINT        NULL,
    [ReqDate]             DATETIME        NULL,
    [CancelDate]          DATETIME        NULL,
    [PickStatus]          VARCHAR (1)     NULL,
    [Pick]                VARCHAR (1)     NULL,
    [BlockDunn]           VARCHAR (1)     NULL,
    [PeyMethod]           NVARCHAR (15)   NULL,
    [PayBlock]            VARCHAR (1)     NULL,
    [PayBlckRef]          INT             NULL,
    [MaxDscn]             VARCHAR (1)     NULL,
    [Reserve]             VARCHAR (1)     NULL,
    [Max1099]             NUMERIC (19, 6) NULL,
    [CntrlBnk]            NVARCHAR (15)   NULL,
    [PickRmrk]            NVARCHAR (254)  NULL,
    [ISRCodLine]          NVARCHAR (53)   NULL,
    [ExpAppl]             NUMERIC (19, 6) NULL,
    [ExpApplFC]           NUMERIC (19, 6) NULL,
    [ExpApplSC]           NUMERIC (19, 6) NULL,
    [Project]             NVARCHAR (20)   NULL,
    [DeferrTax]           VARCHAR (1)     NULL,
    [LetterNum]           NVARCHAR (20)   NULL,
    [FromDate]            DATETIME        NULL,
    [ToDate]              DATETIME        NULL,
    [WTApplied]           NUMERIC (19, 6) NULL,
    [WTAppliedF]          NUMERIC (19, 6) NULL,
    [BoeReserev]          VARCHAR (1)     NULL,
    [AgentCode]           NVARCHAR (32)   NULL,
    [WTAppliedS]          NUMERIC (19, 6) NULL,
    [EquVatSum]           NUMERIC (19, 6) NULL,
    [EquVatSumF]          NUMERIC (19, 6) NULL,
    [EquVatSumS]          NUMERIC (19, 6) NULL,
    [Installmnt]          SMALLINT        NULL,
    [VATFirst]            VARCHAR (1)     NULL,
    [NnSbAmnt]            NUMERIC (19, 6) NULL,
    [NnSbAmntSC]          NUMERIC (19, 6) NULL,
    [NbSbAmntFC]          NUMERIC (19, 6) NULL,
    [ExepAmnt]            NUMERIC (19, 6) NULL,
    [ExepAmntSC]          NUMERIC (19, 6) NULL,
    [ExepAmntFC]          NUMERIC (19, 6) NULL,
    [VatDate]             DATETIME        NULL,
    [CorrExt]             NVARCHAR (25)   NULL,
    [CorrInv]             INT             NULL,
    [NCorrInv]            INT             NULL,
    [CEECFlag]            VARCHAR (1)     NULL,
    [BaseAmnt]            NUMERIC (19, 6) NULL,
    [BaseAmntSC]          NUMERIC (19, 6) NULL,
    [BaseAmntFC]          NUMERIC (19, 6) NULL,
    [CtlAccount]          NVARCHAR (15)   NULL,
    [BPLId]               INT             NULL,
    [BPLName]             NVARCHAR (100)  NULL,
    [VATRegNum]           NVARCHAR (32)   NULL,
    [TxInvRptNo]          NVARCHAR (10)   NULL,
    [TxInvRptDt]          DATETIME        NULL,
    [KVVATCode]           NVARCHAR (MAX)  NULL,
    [WTDetails]           NVARCHAR (100)  NULL,
    [SumAbsId]            INT             NULL,
    [SumRptDate]          DATETIME        NULL,
    [PIndicator]          NVARCHAR (10)   NULL,
    [ManualNum]           NVARCHAR (20)   NULL,
    [UseShpdGd]           VARCHAR (1)     NULL,
    [BaseVtAt]            NUMERIC (19, 6) NULL,
    [BaseVtAtSC]          NUMERIC (19, 6) NULL,
    [BaseVtAtFC]          NUMERIC (19, 6) NULL,
    [NnSbVAt]             NUMERIC (19, 6) NULL,
    [NnSbVAtSC]           NUMERIC (19, 6) NULL,
    [NbSbVAtFC]           NUMERIC (19, 6) NULL,
    [ExptVAt]             NUMERIC (19, 6) NULL,
    [ExptVAtSC]           NUMERIC (19, 6) NULL,
    [ExptVAtFC]           NUMERIC (19, 6) NULL,
    [LYPmtAt]             NUMERIC (19, 6) NULL,
    [LYPmtAtSC]           NUMERIC (19, 6) NULL,
    [LYPmtAtFC]           NUMERIC (19, 6) NULL,
    [ExpAnSum]            NUMERIC (19, 6) NULL,
    [ExpAnSys]            NUMERIC (19, 6) NULL,
    [ExpAnFrgn]           NUMERIC (19, 6) NULL,
    [DocSubType]          NVARCHAR (2)    NULL,
    [DpmStatus]           VARCHAR (1)     NULL,
    [DpmAmnt]             NUMERIC (19, 6) NULL,
    [DpmAmntSC]           NUMERIC (19, 6) NULL,
    [DpmAmntFC]           NUMERIC (19, 6) NULL,
    [DpmDrawn]            VARCHAR (1)     NULL,
    [DpmPrcnt]            NUMERIC (19, 6) NULL,
    [PaidSum]             NUMERIC (19, 6) NULL,
    [PaidSumFc]           NUMERIC (19, 6) NULL,
    [PaidSumSc]           NUMERIC (19, 6) NULL,
    [FolioPref]           NVARCHAR (4)    NULL,
    [FolioNum]            INT             NULL,
    [DpmAppl]             NUMERIC (19, 6) NULL,
    [DpmApplFc]           NUMERIC (19, 6) NULL,
    [DpmApplSc]           NUMERIC (19, 6) NULL,
    [LPgFolioN]           INT             NULL,
    [Header]              NVARCHAR (MAX)  NULL,
    [Footer]              NVARCHAR (MAX)  NULL,
    [Posted]              VARCHAR (1)     NULL,
    [OwnerCode]           INT             NULL,
    [BPChCode]            NVARCHAR (15)   NULL,
    [BPChCntc]            INT             NULL,
    [PayToCode]           NVARCHAR (50)   NULL,
    [IsPaytoBnk]          VARCHAR (1)     NULL,
    [BnkCntry]            NVARCHAR (3)    NULL,
    [BankCode]            NVARCHAR (30)   NULL,
    [BnkAccount]          NVARCHAR (50)   NULL,
    [BnkBranch]           NVARCHAR (50)   NULL,
    [isIns]               VARCHAR (1)     NULL,
    [TrackNo]             NVARCHAR (30)   NULL,
    [VersionNum]          NVARCHAR (11)   NULL,
    [LangCode]            INT             NULL,
    [BPNameOW]            VARCHAR (1)     NULL,
    [BillToOW]            VARCHAR (1)     NULL,
    [ShipToOW]            VARCHAR (1)     NULL,
    [RetInvoice]          VARCHAR (1)     NULL,
    [ClsDate]             DATETIME        NULL,
    [MInvNum]             INT             NULL,
    [MInvDate]            DATETIME        NULL,
    [SeqCode]             SMALLINT        NULL,
    [Serial]              INT             NULL,
    [SeriesStr]           NVARCHAR (3)    NULL,
    [SubStr]              NVARCHAR (3)    NULL,
    [Model]               NVARCHAR (6)    NULL,
    [TaxOnExp]            NUMERIC (19, 6) NULL,
    [TaxOnExpFc]          NUMERIC (19, 6) NULL,
    [TaxOnExpSc]          NUMERIC (19, 6) NULL,
    [TaxOnExAp]           NUMERIC (19, 6) NULL,
    [TaxOnExApF]          NUMERIC (19, 6) NULL,
    [TaxOnExApS]          NUMERIC (19, 6) NULL,
    [LastPmnTyp]          VARCHAR (1)     NULL,
    [LndCstNum]           INT             NULL,
    [UseCorrVat]          VARCHAR (1)     NULL,
    [BlkCredMmo]          VARCHAR (1)     NULL,
    [OpenForLaC]          VARCHAR (1)     NULL,
    [Excised]             VARCHAR (1)     NULL,
    [ExcRefDate]          DATETIME        NULL,
    [ExcRmvTime]          NVARCHAR (8)    NULL,
    [SrvGpPrcnt]          NUMERIC (19, 6) NULL,
    [DepositNum]          INT             NULL,
    [CertNum]             NVARCHAR (31)   NULL,
    [DutyStatus]          VARCHAR (1)     NULL,
    [AutoCrtFlw]          VARCHAR (1)     NULL,
    [FlwRefDate]          DATETIME        NULL,
    [FlwRefNum]           NVARCHAR (100)  NULL,
    [VatJENum]            INT             NULL,
    [DpmVat]              NUMERIC (19, 6) NULL,
    [DpmVatFc]            NUMERIC (19, 6) NULL,
    [DpmVatSc]            NUMERIC (19, 6) NULL,
    [DpmAppVat]           NUMERIC (19, 6) NULL,
    [DpmAppVatF]          NUMERIC (19, 6) NULL,
    [DpmAppVatS]          NUMERIC (19, 6) NULL,
    [InsurOp347]          VARCHAR (1)     NULL,
    [IgnRelDoc]           VARCHAR (1)     NULL,
    [BuildDesc]           NVARCHAR (50)   NULL,
    [ResidenNum]          VARCHAR (1)     NULL,
    [Checker]             INT             NULL,
    [Payee]               INT             NULL,
    [CopyNumber]          INT             NULL,
    [SSIExmpt]            VARCHAR (1)     NULL,
    [PQTGrpSer]           SMALLINT        NULL,
    [PQTGrpNum]           INT             NULL,
    [PQTGrpHW]            VARCHAR (1)     NULL,
    [ReopOriDoc]          VARCHAR (1)     NULL,
    [ReopManCls]          VARCHAR (1)     NULL,
    [DocManClsd]          VARCHAR (1)     NULL,
    [ClosingOpt]          SMALLINT        NULL,
    [SpecDate]            DATETIME        NULL,
    [Ordered]             VARCHAR (1)     NULL,
    [NTSApprov]           VARCHAR (1)     NULL,
    [NTSWebSite]          SMALLINT        NULL,
    [NTSeTaxNo]           NVARCHAR (50)   NULL,
    [NTSApprNo]           NVARCHAR (50)   NULL,
    [PayDuMonth]          VARCHAR (1)     NULL,
    [ExtraMonth]          SMALLINT        NULL,
    [ExtraDays]           SMALLINT        NULL,
    [CdcOffset]           SMALLINT        NULL,
    [SignMsg]             NVARCHAR (MAX)  NULL,
    [SignDigest]          NVARCHAR (MAX)  NULL,
    [CertifNum]           NVARCHAR (50)   NULL,
    [KeyVersion]          INT             NULL,
    [EDocGenTyp]          VARCHAR (1)     NULL,
    [ESeries]             SMALLINT        NULL,
    [EDocNum]             NVARCHAR (50)   NULL,
    [EDocExpFrm]          INT             NULL,
    [OnlineQuo]           VARCHAR (1)     NULL,
    [POSEqNum]            NVARCHAR (20)   NULL,
    [POSManufSN]          NVARCHAR (20)   NULL,
    [POSCashN]            INT             NULL,
    [EDocStatus]          VARCHAR (1)     NULL,
    [EDocCntnt]           NVARCHAR (MAX)  NULL,
    [EDocProces]          VARCHAR (1)     NULL,
    [EDocErrCod]          NVARCHAR (50)   NULL,
    [EDocErrMsg]          NVARCHAR (MAX)  NULL,
    [EDocCancel]          VARCHAR (1)     NULL,
    [EDocTest]            VARCHAR (1)     NULL,
    [EDocPrefix]          NVARCHAR (10)   NULL,
    [CUP]                 INT             NULL,
    [CIG]                 INT             NULL,
    [DpmAsDscnt]          VARCHAR (1)     NULL,
    [Attachment]          NVARCHAR (MAX)  NULL,
    [AtcEntry]            INT             NULL,
    [SupplCode]           NVARCHAR (254)  NULL,
    [GTSRlvnt]            VARCHAR (1)     NULL,
    [BaseDisc]            NUMERIC (19, 6) NULL,
    [BaseDiscSc]          NUMERIC (19, 6) NULL,
    [BaseDiscFc]          NUMERIC (19, 6) NULL,
    [BaseDiscPr]          NUMERIC (19, 6) NULL,
    [CreateTS]            INT             NULL,
    [UpdateTS]            INT             NULL,
    [SrvTaxRule]          VARCHAR (1)     NULL,
    [AnnInvDecR]          INT             NULL,
    [Supplier]            NVARCHAR (15)   NULL,
    [Releaser]            INT             NULL,
    [Receiver]            INT             NULL,
    [ToWhsCode]           NVARCHAR (8)    NULL,
    [AssetDate]           DATETIME        NULL,
    [Requester]           NVARCHAR (25)   NULL,
    [ReqName]             NVARCHAR (155)  NULL,
    [Branch]              SMALLINT        NULL,
    [Department]          SMALLINT        NULL,
    [Email]               NVARCHAR (100)  NULL,
    [Notify]              VARCHAR (1)     NULL,
    [ReqType]             INT             NULL,
    [OriginType]          VARCHAR (1)     NULL,
    [IsReuseNum]          VARCHAR (1)     NULL,
    [IsReuseNFN]          VARCHAR (1)     NULL,
    [DocDlvry]            VARCHAR (1)     NULL,
    [PaidDpm]             NUMERIC (19, 6) NULL,
    [PaidDpmF]            NUMERIC (19, 6) NULL,
    [PaidDpmS]            NUMERIC (19, 6) NULL,
    [EnvTypeNFe]          INT             NULL,
    [AgrNo]               INT             NULL,
    [IsAlt]               VARCHAR (1)     NULL,
    [AltBaseTyp]          INT             NULL,
    [AltBaseEnt]          INT             NULL,
    [AuthCode]            NVARCHAR (250)  NULL,
    [StDlvDate]           DATETIME        NULL,
    [StDlvTime]           INT             NULL,
    [EndDlvDate]          DATETIME        NULL,
    [EndDlvTime]          INT             NULL,
    [VclPlate]            NVARCHAR (20)   NULL,
    [ElCoStatus]          NVARCHAR (10)   NULL,
    [AtDocType]           NVARCHAR (2)    NULL,
    [ElCoMsg]             NVARCHAR (254)  NULL,
    [PrintSEPA]           VARCHAR (1)     NULL,
    [FreeChrg]            NUMERIC (19, 6) NULL,
    [FreeChrgFC]          NUMERIC (19, 6) NULL,
    [FreeChrgSC]          NUMERIC (19, 6) NULL,
    [NfeValue]            NUMERIC (19, 6) NULL,
    [FiscDocNum]          NVARCHAR (100)  NULL,
    [RelatedTyp]          INT             NULL,
    [RelatedEnt]          INT             NULL,
    [CCDEntry]            INT             NULL,
    [NfePrntFo]           INT             NULL,
    [ZrdAbs]              INT             NULL,
    [POSRcptNo]           INT             NULL,
    [FoCTax]              NUMERIC (19, 6) NULL,
    [FoCTaxFC]            NUMERIC (19, 6) NULL,
    [FoCTaxSC]            NUMERIC (19, 6) NULL,
    [TpCusPres]           INT             NULL,
    [ExcDocDate]          DATETIME        NULL,
    [FoCFrght]            NUMERIC (19, 6) NULL,
    [FoCFrghtFC]          NUMERIC (19, 6) NULL,
    [FoCFrghtSC]          NUMERIC (19, 6) NULL,
    [InterimTyp]          SMALLINT        NULL,
    [PTICode]             NVARCHAR (5)    NULL,
    [Letter]              VARCHAR (1)     NULL,
    [FolNumFrom]          INT             NULL,
    [FolNumTo]            INT             NULL,
    [FolSeries]           INT             NULL,
    [SplitTax]            NUMERIC (19, 6) NULL,
    [SplitTaxFC]          NUMERIC (19, 6) NULL,
    [SplitTaxSC]          NUMERIC (19, 6) NULL,
    [ToBinCode]           NVARCHAR (228)  NULL,
    [PermitNo]            NVARCHAR (20)   NULL,
    [MYFtype]             NVARCHAR (2)    NULL,
    [PoDropPrss]          VARCHAR (1)     NULL,
    [DocTaxID]            NVARCHAR (32)   NULL,
    [DateReport]          DATETIME        NULL,
    [RepSection]          NVARCHAR (3)    NULL,
    [ExclTaxRep]          VARCHAR (1)     NULL,
    [PosCashReg]          INT             NULL,
    [DmpTransID]          NVARCHAR (20)   NULL,
    [ECommerBP]           NVARCHAR (15)   NULL,
    [EComerGSTN]          NVARCHAR (15)   NULL,
    [Revision]            VARCHAR (1)     NULL,
    [RevRefNo]            NVARCHAR (100)  NULL,
    [RevRefDate]          DATETIME        NULL,
    [RevCreRefN]          NVARCHAR (100)  NULL,
    [RevCreRefD]          DATETIME        NULL,
    [TaxInvNo]            NVARCHAR (100)  NULL,
    [FrmBpDate]           DATETIME        NULL,
    [GSTTranTyp]          NVARCHAR (2)    NULL,
    [BaseType]            INT             NULL,
    [BaseEntry]           INT             NULL,
    [U_PUR_LEVEL]         NVARCHAR (15)   NULL,
    [U_DP_REQ]            NVARCHAR (10)   NULL,
    [U_VENDOR_ACCPT]      NVARCHAR (10)   NULL,
    [U_VENDOR_ACCP_ATTCH] NVARCHAR (MAX)  NULL,
    [U_U_INTC_ACC]        INT             NULL,
    [U_U_PAY_BNK_ACC]     NVARCHAR (10)   NULL,
    [U_TRSR_COUNTRY]      NVARCHAR (10)   NULL,
    [U_QUOTE_ONLY]        NVARCHAR (10)   NULL,
    [U_PAY_STATUS]        NVARCHAR (10)   NULL,
    [U_PAY_NUM]           NVARCHAR (25)   NULL,
    [U_DATE_DIS]          DATETIME        NULL,
    [U_COR_BW_FromDate]   DATETIME        NULL,
    [U_COR_BW_ToDate]     DATETIME        NULL,
    [U_PRTY_LVL]          NVARCHAR (20)   NULL,
    [U_LANDED_CST_PO]     INT             NULL,
    [U_TRSFR_LC_NO]       INT             NULL,
    [U_DP_PER]            NUMERIC (19, 6) NULL,
    [U_I1_PER]            NUMERIC (19, 6) NULL,
    [U_I2_PER]            NUMERIC (19, 6) NULL,
    [U_I3_PER]            NUMERIC (19, 6) NULL,
    [U_I4_PER]            NUMERIC (19, 6) NULL,
    [U_I5_PER]            NUMERIC (19, 6) NULL,
    [U_APP_DOC_ATTCH]     NVARCHAR (MAX)  NULL,
    [U_REQUEST_APP]       NVARCHAR (10)   NULL,
    [U_PAYEE_NAME]        NVARCHAR (50)   NULL,
    [U_PAYEE_BANK]        NVARCHAR (100)  NULL,
    [U_PAY_BANK_ACC_NO]   NVARCHAR (25)   NULL,
    [U_DP2_PER]           NUMERIC (19, 6) NULL,
    [U_DP3_PER]           NUMERIC (19, 6) NULL,
    [U_USE_DP]            INT             NULL,
    [U_BANK_CODE]         NVARCHAR (25)   NULL,
    [U_ARRec]             NVARCHAR (10)   NULL,
    [U_Approver]          NVARCHAR (50)   NULL,
    [U_PAYMENT]           NVARCHAR (10)   NULL,
    [CountryCode]         NVARCHAR (3)    NULL
);

