CREATE TABLE [dbo].[OutgoingPayments] (
    [CANCELED]                   VARCHAR (1)     NULL,
    [TransId]                    INT             NULL,
    [UserSign]                   SMALLINT        NULL,
    [OwnerCode]                  INT             NULL,
    [U_PAYEE_NAME]               NVARCHAR (50)   NULL,
    [U_IN_BANK]                  NVARCHAR (100)  NULL,
    [U_BANK_ACCT_NO]             NVARCHAR (25)   NULL,
    [U_UPLOAD_STS]               NVARCHAR (15)   NULL,
    [U_IN_PAY_APP]               NVARCHAR (10)   NULL,
    [U_PAYMENT_RUN]              INT             NULL,
    [U_ATTCH1]                   NVARCHAR (MAX)  NULL,
    [U_ATTCH2]                   NVARCHAR (MAX)  NULL,
    [DocumentEntry]              INT             NULL,
    [DocumentNumber]             INT             NULL,
    [DocumentDate]               DATETIME        NULL,
    [TransferAccount]            NVARCHAR (15)   NULL,
    [BusinessPartnerCode]        NVARCHAR (15)   NULL,
    [BusinessPartnerName]        NVARCHAR (100)  NULL,
    [DocumentType]               VARCHAR (1)     NULL,
    [BPAccount]                  NVARCHAR (15)   NULL,
    [DocumentTotal]              NUMERIC (19, 6) NULL,
    [DocumentTotalSC]            NUMERIC (19, 6) NULL,
    [JournalRemarks]             NVARCHAR (50)   NULL,
    [PaidInSC]                   NUMERIC (19, 6) NULL,
    [InvoiceCategory]            NVARCHAR (20)   NULL,
    [DepartmentCode]             NVARCHAR (8)    NULL,
    [LocationCode]               NVARCHAR (8)    NULL,
    [AccountCode]                NVARCHAR (15)   NULL,
    [Desctiption]                NVARCHAR (250)  NULL,
    [DocumentCurrency]           NVARCHAR (3)    NULL,
    [Comments]                   NVARCHAR (254)  NULL,
    [CreateDate]                 DATETIME        NULL,
    [CountryCode]                NVARCHAR (20)   NULL,
    [CountryID]                  INT             NULL,
    [DocumentDateID]             INT             NULL,
    [VendorID]                   INT             NULL,
    [DepartmentID]               INT             NULL,
    [LocationID]                 INT             NULL,
    [UpdateDate]                 DATETIME        NULL,
    [UpdateDateID]               INT             NULL,
    [U_VendorAdd]                NVARCHAR (35)   NULL,
    [U_Bank_Code]                NVARCHAR (40)   NULL,
    [InvoiceID]                  INT             NULL,
    [PaidToInvoice]              NUMERIC (19, 6) NULL,
    [PaidForeignCurrency]        NUMERIC (19, 6) NULL,
    [AppliedWTax]                NUMERIC (19, 6) NULL,
    [AppliedWTaxForeignCurrency] NUMERIC (19, 6) NULL,
    [AppliedWTaxSystemCurrency]  NUMERIC (19, 6) NULL,
    [RowNumber]                  INT             NULL,
    [GrossAmount]                NUMERIC (19, 6) NULL,
    [GrossAmountForeignCurrency] NUMERIC (19, 6) NULL,
    [GrossAmountSystemCurrency]  NUMERIC (19, 6) NULL,
    [BaseDocumentEntry]          INT             NULL,
    [U_BP_Confd]                 NVARCHAR (5)    NULL,
    [U_ICTrgNo]                  INT             NULL,
    [U_ICTrgCntry]               NVARCHAR (10)   NULL,
    [U_ICRemarks]                NVARCHAR (150)  NULL
);

