CREATE TABLE [dbo].[PurchaseOrders] (
    [CountryCode]                  NVARCHAR (20)   NULL,
    [ItemCode]                     NVARCHAR (50)   NULL,
    [Currency]                     NVARCHAR (3)    NULL,
    [DocumentNumber]               INT             NULL,
    [BusinessPartnerCode]          NVARCHAR (15)   NULL,
    [BusinessPartnerName]          NVARCHAR (100)  NULL,
    [DocumentOwner]                INT             NULL,
    [CustomerSatisfaction]         NVARCHAR (50)   NULL,
    [DocumentStatus]               VARCHAR (1)     NULL,
    [AttachmentEntry]              INT             NULL,
    [RowNumber]                    INT             NULL,
    [BaseRow]                      INT             NULL,
    [RowTotal]                     NUMERIC (19, 6) NULL,
    [DepartmentCode]               NVARCHAR (8)    NULL,
    [LocationCode]                 NVARCHAR (8)    NULL,
    [SalesEmployeeCode]            INT             NULL,
    [Price]                        NUMERIC (19, 6) NULL,
    [TargetType]                   INT             NULL,
    [U_Approver]                   NVARCHAR (50)   NULL,
    [DocumentEntry]                INT             NULL,
    [DocumentDate]                 DATETIME        NULL,
    [UserSignature]                SMALLINT        NULL,
    [DocumentManuallyClosed]       VARCHAR (1)     NULL,
    [CreateDate]                   DATETIME        NULL,
    [U_TRSR_Country]               NVARCHAR (10)   NULL,
    [Canceled]                     VARCHAR (1)     NULL,
    [DocumentDueDate]              DATETIME        NULL,
    [DocumentCurrency]             NVARCHAR (3)    NULL,
    [DocumentTotalForeignCurrency] NUMERIC (19, 6) NULL,
    [DocumentTotal]                NUMERIC (19, 6) NULL,
    [PaidToDate]                   NUMERIC (19, 6) NULL,
    [U_U_DP_Date]                  DATETIME        NULL,
    [U_Season]                     NVARCHAR (50)   NULL,
    [Comments]                     NVARCHAR (254)  NULL,
    [PaidForeignCurrency]          NUMERIC (19, 6) NULL,
    [U_I1_Date]                    DATETIME        NULL,
    [U_I1_PER]                     NUMERIC (19, 6) NULL,
    [U_I2_Date]                    DATETIME        NULL,
    [U_I2_Per]                     NUMERIC (19, 6) NULL,
    [U_I4_Date]                    DATETIME        NULL,
    [U_I4_Per]                     NUMERIC (19, 6) NULL,
    [U_I5_Date]                    DATETIME        NULL,
    [U_I5_Per]                     NUMERIC (19, 6) NULL,
    [U_TRSFR_LC_NO]                INT             NULL,
    [U_InputsApprover]             NVARCHAR (3)    NULL,
    [DocumentDraftInternalID]      INT             NULL,
    [UpdateDate]                   DATETIME        NULL,
    [BaseDocumentType]             INT             NULL,
    [RowTotalUSD]                  NUMERIC (19, 6) NULL,
    [PurQuotationRequiredDate]     DATETIME        NULL,
    [RowStatus]                    VARCHAR (1)     NULL,
    [AccountCode]                  NVARCHAR (15)   NULL,
    [Quantity]                     NUMERIC (19, 6) NULL,
    [BaseDocumentReference]        NVARCHAR (16)   NULL,
    [u_webPRID]                    INT             NULL,
    [WarehouseStatus]              VARCHAR (1)     NULL,
    [Description]                  NVARCHAR (100)  NULL,
    [Text]                         NVARCHAR (MAX)  NULL,
    [WarehouseCode]                NVARCHAR (8)    NULL,
    [RowTotalForeignCurrency]      NUMERIC (19, 6) NULL,
    [InventoryQuantity]            NUMERIC (19, 6) NULL,
    [OpenInventoryQuantity]        NUMERIC (19, 6) NULL,
    [FreeText]                     NVARCHAR (100)  NULL,
    [UoMCode]                      NVARCHAR (20)   NULL,
    [RemainingOpenQuantitiy]       NUMERIC (19, 6) NULL,
    [U_Requestor]                  NVARCHAR (50)   NULL,
    [DiscountPercentage]           NUMERIC (19, 6) NULL,
    [UnitPrice]                    NUMERIC (19, 6) NULL,
    [ObjectType]                   NVARCHAR (20)   NULL,
    [GrossPrice]                   NUMERIC (19, 6) NULL,
    [TotalTax]                     NUMERIC (19, 6) NULL,
    [TaxAmountUSD]                 NUMERIC (19, 6) NULL,
    [GrossTotal]                   NUMERIC (19, 6) NULL,
    [GrossTotalUSD]                NUMERIC (19, 6) NULL,
    [DocumentDateID]               INT             NULL,
    [CreateDateID]                 INT             NULL,
    [ItemID]                       INT             NULL,
    [CurrencyID]                   INT             NULL,
    [DepartmentID]                 INT             NULL,
    [LocationID]                   INT             NULL,
    [CountryID]                    INT             NULL,
    [VendorID]                     INT             NULL,
    [UpdateDateID]                 INT             NULL,
    [DocumentDueDateID]            INT             NULL,
    [RequiredDateID]               INT             NULL,
    [AccountID]                    INT             NULL,
    [U_I3_Per]                     NUMERIC (19, 6) NULL,
    [U_U_PT_INS]                   NVARCHAR (200)  NULL,
    [U_WebProcNumber]              INT             NULL,
    [U_VendorPerf]                 NVARCHAR (254)  NULL,
    [U_VendorComment]              NVARCHAR (254)  NULL,
    [U_Payment_Request_Date]       DATETIME        NULL,
    [U_Purchaser]                  NVARCHAR (30)   NULL,
    [VatSumFrgn]                   NUMERIC (19, 6) NULL,
    [GrossTotalForeignCurrency]    NUMERIC (19, 6) NULL,
    [BaseDocumentEntry]            INT             NULL,
    [CreateTime]                   INT             NULL,
    [UpdateTime]                   INT             NULL,
    [UserSignature2]               SMALLINT        NULL,
    [DocumentSubmissionDate]       DATETIME        NULL,
    [ItemName]                     NVARCHAR (100)  NULL
);

