CREATE TABLE [dbo].[PurchaseRequestPortal] (
    [PurchaseRequestId]       INT             NULL,
    [Requester]               NVARCHAR (201)  NULL,
    [Approver]                NVARCHAR (201)  NULL,
    [Purchaser]               NVARCHAR (201)  NULL,
    [Country]                 NVARCHAR (MAX)  NULL,
    [CreatedDate]             DATETIME2 (7)   NULL,
    [DeliveryDate]            DATETIME2 (7)   NULL,
    [Currency]                NVARCHAR (MAX)  NULL,
    [Department]              NVARCHAR (MAX)  NULL,
    [Location]                NVARCHAR (MAX)  NULL,
    [Delivery Location]       NVARCHAR (MAX)  NULL,
    [Warehouse]               NVARCHAR (100)  NULL,
    [PurchasePriority]        NVARCHAR (MAX)  NULL,
    [Quantity]                INT             NULL,
    [UnitPrice]               NUMERIC (18, 3) NULL,
    [TotalCost]               NUMERIC (29, 2) NULL,
    [USDCost]                 NUMERIC (38, 7) NULL,
    [FXRate]                  NUMERIC (13, 4) NULL,
    [Vendor]                  NVARCHAR (100)  NULL,
    [Status]                  NVARCHAR (MAX)  NULL,
    [Status Sort]             INT             NULL,
    [Item]                    NVARCHAR (100)  NULL,
    [Item Category]           NVARCHAR (MAX)  NULL,
    [ItemSubGroup]            NVARCHAR (40)   NULL,
    [Comments]                NVARCHAR (MAX)  NULL,
    [ReceivedQuantity]        INT             NULL,
    [RemainingQuantity]       INT             NULL,
    [GoodsIssueID]            INT             NULL,
    [ServicedByFlag]          VARCHAR (9)     NULL,
    [Approver Email]          NVARCHAR (256)  NULL,
    [Requester Email]         NVARCHAR (256)  NULL,
    [# of Goods Issues]       INT             NULL,
    [ProjectId]               INT             NULL,
    [PurchaseRequestHeaderId] INT             NULL,
    [PurchaseOrderLineId]     INT             NULL,
    [SAPPurchaseOrderID]      INT             NULL,
    [PurchaseRequestType]     NVARCHAR (MAX)  NULL
);

