CREATE TABLE [dbo].[StaffExpenses] (
    [Period]         INT             NULL,
    [Instance]       SMALLINT        NULL,
    [Series]         INT             NULL,
    [Handwrtten]     VARCHAR (1)     NULL,
    [Canceled]       VARCHAR (1)     NULL,
    [Object]         NVARCHAR (20)   NULL,
    [LogInst]        INT             NULL,
    [Transfered]     VARCHAR (1)     NULL,
    [Status]         VARCHAR (1)     NULL,
    [CreateDate]     DATETIME        NULL,
    [CreateTime]     SMALLINT        NULL,
    [UpdateDate]     DATETIME        NULL,
    [UpdateTime]     SMALLINT        NULL,
    [DataSource]     VARCHAR (1)     NULL,
    [RequestStatus]  VARCHAR (1)     NULL,
    [Creator]        NVARCHAR (8)    NULL,
    [Remark]         NVARCHAR (MAX)  NULL,
    [U_REMARKS]      NVARCHAR (MAX)  NULL,
    [U_DATE]         DATETIME        NULL,
    [U_BK]           NVARCHAR (30)   NULL,
    [U_TRSR_ALT]     NVARCHAR (35)   NULL,
    [U_AUTO_STS]     NVARCHAR (40)   NULL,
    [U_AUTO_BANK]    NVARCHAR (7)    NULL,
    [U_ATTCH1]       NVARCHAR (MAX)  NULL,
    [U_ATTCH2]       NVARCHAR (MAX)  NULL,
    [U_REQUEST_ID]   NVARCHAR (25)   NULL,
    [U_REQ_NAME]     NVARCHAR (50)   NULL,
    [U_PaidDate]     DATETIME        NULL,
    [U_ROW_NO]       SMALLINT        NULL,
    [U_ACCTCODE]     INT             NULL,
    [U_ACCTNAME]     NVARCHAR (100)  NULL,
    [U_DEBIT]        NUMERIC (19, 6) NULL,
    [U_CREDIT]       NUMERIC (19, 6) NULL,
    [U_DIM1_CLASS]   NVARCHAR (10)   NULL,
    [U_DIM2_DEPTT]   NVARCHAR (25)   NULL,
    [U_DIM3_LOC]     NVARCHAR (25)   NULL,
    [U_STATUS]       NVARCHAR (35)   NULL,
    [U_PAYEE_NAME]   NVARCHAR (50)   NULL,
    [U_BANK_NAME]    NVARCHAR (100)  NULL,
    [U_BANK_ACCT_NO] NVARCHAR (20)   NULL,
    [U_PROJECT]      NVARCHAR (15)   NULL,
    [U_EXP_DETAIL]   NVARCHAR (MAX)  NULL,
    [U_PAY_NUM]      NVARCHAR (25)   NULL,
    [U_LINE_STATUS]  NVARCHAR (10)   NULL,
    [U_CR_ACC]       INT             NULL,
    [U_CR_ACC_NAME]  NVARCHAR (40)   NULL,
    [U_BNK_CODE]     NVARCHAR (20)   NULL,
    [U_NAT_ID]       NVARCHAR (20)   NULL,
    [U_LINE_APP]     NVARCHAR (10)   NULL,
    [U_BANK_CODE]    NVARCHAR (10)   NULL,
    [U_UPLOAD_STS]   NVARCHAR (15)   NULL,
    [U_PAYMENT_RUN]  INT             NULL,
    [U_WIP_PROJECT]  NVARCHAR (50)   NULL,
    [DocumentEntry]  INT             NULL,
    [DocumentNumber] INT             NULL,
    [UserSignature]  INT             NULL,
    [RowNumber]      INT             NULL,
    [VisualOrder]    INT             NULL,
    [BankExportDate] DATETIME        NULL,
    [CountryCode]    NVARCHAR (2)    NULL,
    [U_Approver]     NVARCHAR (50)   NULL
);


GO
CREATE NONCLUSTERED INDEX [ix_CountryCode_DocumentEntry_RowNumber]
    ON [dbo].[StaffExpenses]([CountryCode] ASC, [DocumentEntry] ASC, [RowNumber] ASC);

